MANUAL_TESTS = """
{q:"What does 'passport' mean?",opts:["паспорт","билет","ключ","дверь"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'apple' mean?",opts:["яблоко","груша","апельсин","банан"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'water' mean?",opts:["вода","сок","молоко","чай"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'house' mean?",opts:["дом","квартира","улица","город"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'cat' mean?",opts:["кошка","собака","птица","рыба"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'book' mean?",opts:["книга","тетрадь","ручка","стол"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'table' mean?",opts:["стол","стул","окно","дверь"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'dog' mean?",opts:["собака","кошка","лошадь","корова"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'school' mean?",opts:["школа","университет","больница","магазин"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'mother' mean?",opts:["мать","отец","сестра","брат"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'friend' mean?",opts:["друг","враг","сосед","коллега"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'red' mean?",opts:["красный","синий","зелёный","жёлтый"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'big' mean?",opts:["большой","маленький","высокий","низкий"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'happy' mean?",opts:["счастливый","грустный","злой","усталый"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Which is correct: 'She ___ a teacher'?",opts:["is","are","am","be"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Which is correct: 'I ___ from Russia'?",opts:["am","is","are","be"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Which is correct: 'They ___ students'?",opts:["are","is","am","be"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What is the plural of 'cat'?",opts:["cats","cates","cat","catses"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What is the plural of 'book'?",opts:["books","bookes","book","bookies"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"How do you say 'hello' in a formal way?",opts:["Good morning","Hey","Yo","Howdy"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'goodbye' mean?",opts:["до свидания","здравствуйте","спасибо","пожалуйста"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'please' mean?",opts:["пожалуйста","спасибо","извините","нет"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'thank you' mean?",opts:["спасибо","пожалуйста","привет","пока"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What number comes after 'nine'?",opts:["ten","eleven","eight","twelve"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What day comes after Monday?",opts:["Tuesday","Wednesday","Sunday","Thursday"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Which word means 'маленький'?",opts:["small","tall","fast","loud"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Which word means 'быстрый'?",opts:["fast","slow","big","old"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"How do you ask someone their name?",opts:["What is your name?","Where are you?","How old are you?","What do you do?"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'yes' mean?",opts:["да","нет","может","всегда"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"What does 'no' mean?",opts:["нет","да","может","никогда"],a:0,lv:"A1",xp:10,type:"choice"},
{q:"Translate to English: «кошка»",a:"cat",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «собака»",a:"dog",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «дом»",a:"house",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «вода»",a:"water",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «яблоко»",a:"apple",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «книга»",a:"book",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «стол»",a:"table",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «мать»",a:"mother",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «отец»",a:"father",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «друг»",a:"friend",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «школа»",a:"school",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «красный»",a:"red",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «большой»",a:"big",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «маленький»",a:"small",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «спасибо»",a:"thank you",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «пожалуйста»",a:"please",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «привет»",a:"hello",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «да»",a:"yes",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «нет»",a:"no",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «один»",a:"one",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «два»",a:"two",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «три»",a:"three",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «белый»",a:"white",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «чёрный»",a:"black",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «синий»",a:"blue",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «зелёный»",a:"green",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «хлеб»",a:"bread",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «молоко»",a:"milk",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «солнце»",a:"sun",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «луна»",a:"moon",lv:"A1",xp:12,type:"input"},
{q:"Translate to English: «рука»",a:"hand",lv:"A1",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"cat",opts:["cat","bat","hat","mat"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"dog",opts:["dog","log","fog","bog"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"book",opts:["book","look","cook","hook"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"house",opts:["house","mouse","louse","blouse"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"school",opts:["school","cool","pool","tool"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"water",opts:["water","later","hater","matter"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"table",opts:["table","cable","fable","able"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"apple",opts:["apple","ample","ample","chapel"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"happy",opts:["happy","nappy","sappy","snappy"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"friend",opts:["friend","fiend","freed","trend"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"red",opts:["red","bed","fed","led"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"big",opts:["big","pig","dig","fig"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"sun",opts:["sun","son","run","fun"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"hand",opts:["hand","band","land","sand"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"milk",opts:["milk","silk","bilk","ilk"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"bread",opts:["bread","bead","breed","tread"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"green",opts:["green","greet","greed","creek"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"moon",opts:["moon","noon","boon","soon"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"blue",opts:["blue","blew","clue","glue"],lv:"A1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"white",opts:["white","write","quite","kite"],lv:"A1",xp:15,type:"listen"},
{q:"What does 'tired' mean?",opts:["усталый","голодный","злой","счастливый"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'hungry' mean?",opts:["голодный","сытый","жаждущий","сонный"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'weather' mean?",opts:["погода","природа","климат","среда"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'shop' mean?",opts:["магазин","завод","офис","склад"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'money' mean?",opts:["деньги","монета","банк","цена"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'early' mean?",opts:["рано","поздно","скоро","долго"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'late' mean?",opts:["поздно","рано","долго","редко"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'beautiful' mean?",opts:["красивый","некрасивый","странный","умный"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'difficult' mean?",opts:["трудный","лёгкий","скучный","интересный"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'always' mean?",opts:["всегда","никогда","иногда","редко"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'sometimes' mean?",opts:["иногда","всегда","никогда","часто"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: 'She ___ to school every day'?",opts:["goes","go","going","gone"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: 'I ___ TV last night'?",opts:["watched","watch","watching","watches"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: 'They ___ playing football now'?",opts:["are","is","am","be"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'beside' mean?",opts:["рядом с","позади","перед","над"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'between' mean?",opts:["между","среди","перед","за"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which word means 'холодный'?",opts:["cold","bold","sold","told"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What is the past tense of 'go'?",opts:["went","goed","gone","going"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What is the past tense of 'eat'?",opts:["ate","eated","eaten","eating"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: 'There ___ two books on the table'?",opts:["are","is","am","be"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'cheap' mean?",opts:["дешёвый","дорогой","бесплатный","редкий"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'expensive' mean?",opts:["дорогой","дешёвый","бесплатный","скидка"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is the correct question: asking where someone lives?",opts:["Where do you live?","Where you live?","Where are you living?","Where live you?"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'borrow' mean?",opts:["взять в долг","одолжить кому-то","купить","продать"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'lend' mean?",opts:["одолжить кому-то","взять в долг","потерять","найти"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What is the opposite of 'open'?",opts:["closed","shut","close","lock"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'noisy' mean?",opts:["шумный","тихий","громкий","слышимый"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'quiet' mean?",opts:["тихий","шумный","молчаливый","спокойный"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: 'He ___ been here before'?",opts:["has","have","had","is"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'journey' mean?",opts:["путешествие","поездка","прогулка","полёт"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'travel' mean?",opts:["путешествовать","ехать","идти","лететь"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Which is correct: '___ you like some tea?",opts:["Would","Do","Should","Could"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'remember' mean?",opts:["помнить","забыть","знать","думать"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'forget' mean?",opts:["забыть","помнить","знать","понять"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"What does 'choose' mean?",opts:["выбирать","терять","находить","брать"],a:0,lv:"A2",xp:10,type:"choice"},
{q:"Translate to English: «погода»",a:"weather",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «деньги»",a:"money",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «усталый»",a:"tired",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «голодный»",a:"hungry",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «магазин»",a:"shop",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «красивый»",a:"beautiful",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «трудный»",a:"difficult",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «всегда»",a:"always",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «иногда»",a:"sometimes",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «холодный»",a:"cold",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «дешёвый»",a:"cheap",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «дорогой»",a:"expensive",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «тихий»",a:"quiet",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «шумный»",a:"noisy",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «путешествовать»",a:"travel",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «помнить»",a:"remember",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «забыть»",a:"forget",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «выбирать»",a:"choose",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «рано»",a:"early",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «поздно»",a:"late",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «между»",a:"between",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «рядом с»",a:"beside",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «взять в долг»",a:"borrow",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «одолжить»",a:"lend",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «путешествие»",a:"journey",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «никогда»",a:"never",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «часто»",a:"often",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «редко»",a:"rarely",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «закрытый»",a:"closed",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «открытый»",a:"open",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «улица»",a:"street",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «больница»",a:"hospital",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «аэропорт»",a:"airport",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «ресторан»",a:"restaurant",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «библиотека»",a:"library",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «почта»",a:"post office",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «словарь»",a:"dictionary",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «ответ»",a:"answer",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «вопрос»",a:"question",lv:"A2",xp:12,type:"input"},
{q:"Translate to English: «проблема»",a:"problem",lv:"A2",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"weather",opts:["weather","whether","wither","leather"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"money",opts:["money","monkey","honey","funny"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"travel",opts:["travel","gravel","level","ravel"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"hungry",opts:["hungry","hurry","angry","Henry"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"beautiful",opts:["beautiful","bountiful","dutiful","useful"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"always",opts:["always","already","almost","also"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"forget",opts:["forget","regret","target","fret"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"remember",opts:["remember","resemble","resent","render"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"between",opts:["between","beneath","beside","beyond"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"journey",opts:["journey","attorney","tourney","journey"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"choose",opts:["choose","cheese","chase","chose"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"early",opts:["early","nearly","barely","merely"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"expensive",opts:["expensive","extensive","expansive","exclusive"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"difficult",opts:["difficult","different","distant","digital"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"quiet",opts:["quiet","quite","quit","quilt"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"borrow",opts:["borrow","barrow","burrow","narrow"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"library",opts:["library","lottery","literary","liberty"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"hospital",opts:["hospital","hostel","hostile","hostile"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"airport",opts:["airport","export","import","report"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"restaurant",opts:["restaurant","resistant","restraint","constant"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"answer",opts:["answer","dancer","cancer","lancer"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"street",opts:["street","sweet","greet","tweet"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"problem",opts:["problem","program","process","product"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"dictionary",opts:["dictionary","documentary","directory","discovery"],lv:"A2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"question",opts:["question","mention","pension","tension"],lv:"A2",xp:15,type:"listen"},
{q:"What does 'although' mean?",opts:["хотя","потому что","если","когда"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'however' mean?",opts:["однако","поэтому","таким образом","например"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'despite' mean?",opts:["несмотря на","из-за","благодаря","вместо"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'suggest' mean?",opts:["предлагать","требовать","приказывать","просить"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'manage' mean?",opts:["справляться","пытаться","начинать","заканчивать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'increase' mean?",opts:["увеличивать","уменьшать","сохранять","изменять"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'decrease' mean?",opts:["уменьшать","увеличивать","оставаться","достигать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'opportunity' mean?",opts:["возможность","проблема","угроза","решение"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'experience' mean?",opts:["опыт","эксперимент","событие","впечатление"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'If I ___ rich, I would travel'?",opts:["were","am","was","be"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'She ___ here for five years'?",opts:["has lived","is living","lives","lived"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'The report ___ written yesterday'?",opts:["was","were","has been","had been"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'reliable' mean?",opts:["надёжный","ненадёжный","возможный","вероятный"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'efficient' mean?",opts:["эффективный","достаточный","необходимый","полезный"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'avoid' mean?",opts:["избегать","игнорировать","отказываться","предотвращать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'establish' mean?",opts:["устанавливать","разрушать","изменять","создавать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'affect' mean?",opts:["влиять","затрагивать","изменять","вредить"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'consider' mean?",opts:["рассматривать","решать","знать","хотеть"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'I wish I ___ speak French'?",opts:["could","can","would","should"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'determine' mean?",opts:["определять","находить","искать","указывать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'pollution' mean?",opts:["загрязнение","катастрофа","экология","климат"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'society' mean?",opts:["общество","страна","культура","нация"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which verb form is correct: 'He ___ to work when it rained'?",opts:["was walking","walked","is walking","walks"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'achieve' mean?",opts:["достигать","получать","хотеть","стараться"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'improve' mean?",opts:["улучшать","изменять","исправлять","развивать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'environment' mean?",opts:["окружающая среда","природа","экология","климат"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'By the time she arrived, he ___ left'?",opts:["had","has","was","would"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'complain' mean?",opts:["жаловаться","возражать","критиковать","ругать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'demand' mean?",opts:["требовать","просить","предлагать","нуждаться"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'prefer' mean?",opts:["предпочитать","выбирать","любить","нравиться"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'admit' mean?",opts:["признавать","отрицать","скрывать","утверждать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'refuse' mean?",opts:["отказывать","соглашаться","принимать","позволять"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'The book ___ on the shelf since Monday'?",opts:["has been","is","was","had been"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'persuade' mean?",opts:["убеждать","заставлять","просить","требовать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'acquire' mean?",opts:["приобретать","терять","продавать","раздавать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'maintain' mean?",opts:["поддерживать","создавать","разрушать","строить"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'She told me that she ___ tired'?",opts:["was","is","has been","were"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'concern' mean?",opts:["беспокойство","интерес","важность","срочность"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'involve' mean?",opts:["включать","исключать","содержать","требовать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'assume' mean?",opts:["предполагать","знать","думать","считать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'estimate' mean?",opts:["оценивать","рассчитывать","измерять","определять"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'occur' mean?",opts:["происходить","повторяться","случаться","возникать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Which is correct: 'Neither she ___ he was at home'?",opts:["nor","or","and","but"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'prevent' mean?",opts:["предотвращать","остановить","запрещать","избегать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'indicate' mean?",opts:["указывать","показывать","объяснять","доказывать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"What does 'intend' mean?",opts:["намереваться","стараться","пытаться","планировать"],a:0,lv:"B1",xp:10,type:"choice"},
{q:"Translate to English: «хотя»",a:"although",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «однако»",a:"however",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «несмотря на»",a:"despite",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «предлагать»",a:"suggest",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «справляться»",a:"manage",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «увеличивать»",a:"increase",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «уменьшать»",a:"decrease",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «возможность»",a:"opportunity",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «опыт»",a:"experience",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «надёжный»",a:"reliable",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «эффективный»",a:"efficient",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «избегать»",a:"avoid",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «устанавливать»",a:"establish",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «влиять»",a:"affect",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «рассматривать»",a:"consider",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «определять»",a:"determine",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «загрязнение»",a:"pollution",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «общество»",a:"society",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «достигать»",a:"achieve",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «улучшать»",a:"improve",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «окружающая среда»",a:"environment",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «жаловаться»",a:"complain",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «требовать»",a:"demand",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «предпочитать»",a:"prefer",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «признавать»",a:"admit",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «отказывать»",a:"refuse",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «убеждать»",a:"persuade",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «приобретать»",a:"acquire",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «поддерживать»",a:"maintain",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «беспокойство»",a:"concern",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «включать»",a:"involve",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «предполагать»",a:"assume",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «оценивать»",a:"estimate",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «происходить»",a:"occur",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «предотвращать»",a:"prevent",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «указывать»",a:"indicate",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «намереваться»",a:"intend",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «внезапно»",a:"suddenly",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «одновременно»",a:"simultaneously",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «последовательно»",a:"consequently",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «предложение»",a:"suggestion",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «решение»",a:"solution",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «результат»",a:"result",lv:"B1",xp:12,type:"input"},
{q:"Translate to English: «причина»",a:"reason",lv:"B1",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"although",opts:["although","all though","all those","altogether"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"however",opts:["however","whoever","wherever","whenever"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"despite",opts:["despite","despise","device","devise"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"opportunity",opts:["opportunity","community","immunity","maturity"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"efficient",opts:["efficient","sufficient","deficient","proficient"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"establish",opts:["establish","abolish","demolish","publish"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"consider",opts:["consider","conceder","conspire","confirm"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"pollution",opts:["pollution","solution","evolution","revolution"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"environment",opts:["environment","enforcement","involvement","achievement"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"persuade",opts:["persuade","pervade","parade","pervade"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"acquire",opts:["acquire","require","inquire","admire"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"maintain",opts:["maintain","attain","contain","obtain"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"society",opts:["society","sobriety","anxiety","variety"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"indicate",opts:["indicate","implicate","intricate","imitate"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"suddenly",opts:["suddenly","studently","subtly","sunnily"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"solution",opts:["solution","pollution","evolution","absolution"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"reason",opts:["reason","season","treason","raisin"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"result",opts:["result","insult","consult","exult"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"improve",opts:["improve","approve","remove","disprove"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"achieve",opts:["achieve","perceive","conceive","believe"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"reliable",opts:["reliable","variable","viable","available"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"demand",opts:["demand","command","remand","expand"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"suggest",opts:["suggest","subject","suspect","sunset"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"prevent",opts:["prevent","present","pretend","percent"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"involve",opts:["involve","evolve","resolve","revolve"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"assume",opts:["assume","consume","resume","costume"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"concern",opts:["concern","concert","confirm","confer"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"experience",opts:["experience","experiment","expression","expedition"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"estimate",opts:["estimate","hesitate","imitate","devastate"],lv:"B1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"occur",opts:["occur","incur","recur","concur"],lv:"B1",xp:15,type:"listen"},
{q:"What does 'ambiguous' mean?",opts:["неоднозначный","непонятный","неизвестный","загадочный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'consequently' mean?",opts:["следовательно","тем не менее","несмотря на это","кроме того"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'substantial' mean?",opts:["существенный","незначительный","разумный","возможный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'elaborate' mean?",opts:["подробный","простой","краткий","сложный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'emphasise' mean?",opts:["подчёркивать","ослаблять","скрывать","упоминать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'appropriate' mean?",opts:["подходящий","неподходящий","возможный","необходимый"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'controversial' mean?",opts:["спорный","бесспорный","известный","важный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'cope with' mean?",opts:["справляться с","избегать","игнорировать","отрицать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'significant' mean?",opts:["значительный","незначительный","особый","конкретный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'negotiate' mean?",opts:["договариваться","соглашаться","обсуждать","решать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: 'Had I known, I ___ told you'?",opts:["would have","would","will have","will"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'acknowledge' mean?",opts:["признавать","отвергать","понимать","осознавать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'inevitable' mean?",opts:["неизбежный","возможный","вероятный","предсказуемый"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'profound' mean?",opts:["глубокий","простой","сложный","важный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: '___ he works hard, he rarely succeeds'?",opts:["Although","Despite","However","Therefore"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'undermine' mean?",opts:["подрывать","укреплять","поддерживать","разрушать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'contradict' mean?",opts:["противоречить","подтверждать","опровергать","отрицать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'persist' mean?",opts:["упорствовать","прекращать","откладывать","продолжать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'manipulate' mean?",opts:["манипулировать","контролировать","использовать","влиять"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: 'She ___ be exhausted after such a long flight'?",opts:["must","should","can","might"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'stimulate' mean?",opts:["стимулировать","подавлять","тормозить","вдохновлять"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'demonstrate' mean?",opts:["демонстрировать","доказывать","объяснять","показывать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: 'The project ___ by the end of the month'?",opts:["will have been completed","will complete","will be completing","is completed"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'perspective' mean?",opts:["перспектива","мнение","взгляд","точка зрения"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'pragmatic' mean?",opts:["прагматичный","практичный","реалистичный","логичный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'initiative' mean?",opts:["инициатива","решение","действие","меры"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'hesitate' mean?",opts:["колебаться","медлить","сомневаться","ждать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'rational' mean?",opts:["рациональный","логичный","разумный","обоснованный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which preposition fits: 'He is responsible ___ the project'?",opts:["for","of","to","with"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'fluctuate' mean?",opts:["колебаться","изменяться","расти","падать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'compromise' mean?",opts:["компромисс","соглашение","уступка","договор"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'skeptical' mean?",opts:["скептически настроенный","критический","недоверчивый","осторожный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'allocate' mean?",opts:["распределять","назначать","выделять","отдавать"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: 'She ___ rather stay home than go out'?",opts:["would","could","should","might"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'surplus' mean?",opts:["излишек","дефицит","запас","резерв"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'momentum' mean?",opts:["импульс","движение","сила","скорость"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'coherent' mean?",opts:["связный","логичный","последовательный","ясный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Which is correct: 'No sooner ___ he left than it started raining'?",opts:["had","has","did","was"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'vague' mean?",opts:["расплывчатый","неясный","неточный","неопределённый"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"What does 'legitimate' mean?",opts:["законный","справедливый","правомерный","официальный"],a:0,lv:"B2",xp:10,type:"choice"},
{q:"Translate to English: «неоднозначный»",a:"ambiguous",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «следовательно»",a:"consequently",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «существенный»",a:"substantial",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «подчёркивать»",a:"emphasise",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «подходящий»",a:"appropriate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «спорный»",a:"controversial",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «значительный»",a:"significant",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «договариваться»",a:"negotiate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «признавать»",a:"acknowledge",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «неизбежный»",a:"inevitable",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «глубокий»",a:"profound",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «подрывать»",a:"undermine",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «противоречить»",a:"contradict",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «упорствовать»",a:"persist",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «манипулировать»",a:"manipulate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «стимулировать»",a:"stimulate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «демонстрировать»",a:"demonstrate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «перспектива»",a:"perspective",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «прагматичный»",a:"pragmatic",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «инициатива»",a:"initiative",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «колебаться»",a:"hesitate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «рациональный»",a:"rational",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «колебаться (в значении меняться)»",a:"fluctuate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «компромисс»",a:"compromise",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «скептически настроенный»",a:"skeptical",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «распределять»",a:"allocate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «излишек»",a:"surplus",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «импульс»",a:"momentum",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «связный»",a:"coherent",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «расплывчатый»",a:"vague",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «законный»",a:"legitimate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «справляться с»",a:"cope with",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «подробный»",a:"elaborate",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «инициатива (взять)»",a:"take the initiative",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «предварительный»",a:"preliminary",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «непрерывный»",a:"continuous",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «пересмотреть»",a:"reconsider",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «ограничение»",a:"limitation",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «внедрение»",a:"implementation",lv:"B2",xp:12,type:"input"},
{q:"Translate to English: «угроза»",a:"threat",lv:"B2",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"ambiguous",opts:["ambiguous","ambitious","analogous","anonymous"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"substantial",opts:["substantial","substandard","substantial","sustainable"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"controversial",opts:["controversial","conversational","conventional","convertible"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"negotiate",opts:["negotiate","navigate","narrate","indicate"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"inevitable",opts:["inevitable","inevitable","invaluable","invariable"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"undermine",opts:["undermine","underline","understate","undergo"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"pragmatic",opts:["pragmatic","dramatic","systematic","automatic"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"fluctuate",opts:["fluctuate","fluctuate","evacuate","evaluate"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"coherent",opts:["coherent","inherent","different","adherent"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"legitimate",opts:["legitimate","illegitimate","illuminate","litigate"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"acknowledge",opts:["acknowledge","knowledge","knowledgeable","accolade"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"contradict",opts:["contradict","contract","contrast","contribute"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"momentum",opts:["momentum","memorandum","modicum","minimum"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"perspective",opts:["perspective","respective","retrospective","prospective"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"allocate",opts:["allocate","advocate","educate","eradicate"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"compromise",opts:["compromise","compose","comprise","promise"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"significant",opts:["significant","magnificent","magnificent","insufficient"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"emphasise",opts:["emphasise","emphasize","empathise","empathize"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"stimulate",opts:["stimulate","simulate","articulate","manipulate"],lv:"B2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"surplus",opts:["surplus","surface","service","sunrise"],lv:"B2",xp:15,type:"listen"},
{q:"What does 'albeit' mean?",opts:["хотя","следовательно","тем не менее","особенно"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'ubiquitous' mean?",opts:["вездесущий","уникальный","универсальный","особенный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'scrutinise' mean?",opts:["тщательно изучать","кратко описывать","просто читать","быстро проверять"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'discrepancy' mean?",opts:["расхождение","различие","несоответствие","ошибка"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'paramount' mean?",opts:["первостепенный","важный","основной","необходимый"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'mitigate' mean?",opts:["смягчать","усиливать","устранять","игнорировать"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'articulate' mean?",opts:["чётко выражать","говорить","объяснять","писать"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'catalyst' mean?",opts:["катализатор","движущая сила","причина","источник"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'cynical' mean?",opts:["циничный","критичный","пессимистичный","недоверчивый"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'dilemma' mean?",opts:["дилемма","проблема","выбор","трудность"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Which is correct: 'Not only ___ she fail the exam, but she also lost her notes'?",opts:["did","had","has","was"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'exploit' mean?",opts:["использовать в корыстных целях","исследовать","развивать","изучать"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'futile' mean?",opts:["тщетный","бесполезный","напрасный","пустой"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Which word best fills: 'The new policy had far-reaching ___'?",opts:["implications","complications","explanations","operations"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'impartial' mean?",opts:["беспристрастный","нейтральный","объективный","справедливый"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'intricate' mean?",opts:["запутанный","сложный","детальный","сложный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'notion' mean?",opts:["понятие","идея","концепция","представление"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Which is correct: '___ the circumstances, we decided to postpone'?",opts:["Given","Despite","Although","Unless"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'obscure' mean?",opts:["малоизвестный","непонятный","тёмный","неясный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'paramount' mean in a sentence about priorities?",opts:["важнее всего","достаточно важный","умеренно важный","немного важный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'prevalent' mean?",opts:["распространённый","популярный","обычный","известный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'refute' mean?",opts:["опровергать","подтверждать","отвергать","опровергать"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Which is correct: 'Seldom ___ such talent'?",opts:["have I seen","I have seen","I saw","did I see"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'tangible' mean?",opts:["ощутимый","понятный","реальный","конкретный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'threshold' mean?",opts:["порог","граница","предел","рубеж"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Which is correct: 'Were it not for her help, we ___ failed'?",opts:["would have","will have","had","would"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'unprecedented' mean?",opts:["беспрецедентный","необычный","уникальный","особенный"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'volatile' mean?",opts:["нестабильный","изменчивый","непредсказуемый","взрывной"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'yield' mean (in economics)?",opts:["доходность","урожай","результат","производить"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"What does 'consensus' mean?",opts:["консенсус","соглашение","единодушие","договор"],a:0,lv:"C1",xp:10,type:"choice"},
{q:"Translate to English: «хотя (хотя и)»",a:"albeit",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «вездесущий»",a:"ubiquitous",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «тщательно изучать»",a:"scrutinise",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «расхождение»",a:"discrepancy",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «первостепенный»",a:"paramount",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «смягчать»",a:"mitigate",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «чётко выражать»",a:"articulate",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «катализатор»",a:"catalyst",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «циничный»",a:"cynical",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «дилемма»",a:"dilemma",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «тщетный»",a:"futile",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «беспристрастный»",a:"impartial",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «запутанный»",a:"intricate",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «понятие»",a:"notion",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «малоизвестный»",a:"obscure",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «распространённый»",a:"prevalent",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «опровергать»",a:"refute",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «ощутимый»",a:"tangible",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «порог»",a:"threshold",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «беспрецедентный»",a:"unprecedented",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «нестабильный»",a:"volatile",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «консенсус»",a:"consensus",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «использовать (в корыстных целях)»",a:"exploit",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «последствия»",a:"implications",lv:"C1",xp:12,type:"input"},
{q:"Translate to English: «доходность»",a:"yield",lv:"C1",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"ubiquitous",opts:["ubiquitous","ambiguous","unanimous","unambiguous"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"scrutinise",opts:["scrutinise","criticise","summarise","categorise"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"discrepancy",opts:["discrepancy","diplomacy","democracy","dependency"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"mitigate",opts:["mitigate","navigate","litigate","irrigate"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"catalyst",opts:["catalyst","catalogue","cataclysm","catapult"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"futile",opts:["futile","fertile","hostile","missile"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"intricate",opts:["intricate","indicate","imitate","intimate"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"prevalent",opts:["prevalent","relevant","equivalent","ambivalent"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"tangible",opts:["tangible","eligible","negligible","flexible"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"unprecedented",opts:["unprecedented","unpredicted","unprotected","unexpected"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"volatile",opts:["volatile","notable","portable","quotable"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"consensus",opts:["consensus","concensus","consent","conserve"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"threshold",opts:["threshold","threadbare","throwback","throughout"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"impartial",opts:["impartial","imperial","immortal","immoral"],lv:"C1",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"notion",opts:["notion","motion","lotion","potion"],lv:"C1",xp:15,type:"listen"},
{q:"What does 'epistemology' mean?",opts:["теория познания","философия бытия","этика","логика"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'equivocate' mean?",opts:["говорить уклончиво","высказываться ясно","противоречить","утверждать"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'exacerbate' mean?",opts:["усугублять","смягчать","устранять","решать"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'inveterate' mean?",opts:["закоренелый","временный","случайный","редкий"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'laconic' mean?",opts:["лаконичный","подробный","чёткий","краткий"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'mendacious' mean?",opts:["лживый","честный","прямой","откровенный"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'obfuscate' mean?",opts:["запутывать","разъяснять","упрощать","скрывать"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'pellucid' mean?",opts:["кристально ясный","туманный","замутнённый","неясный"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"Which is correct: 'So complex was the issue ___ no one could solve it'?",opts:["that","which","as","so"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'recalcitrant' mean?",opts:["непокорный","послушный","упрямый","независимый"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'sycophantic' mean?",opts:["подхалимский","критический","независимый","честный"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'tendentious' mean?",opts:["тенденциозный","нейтральный","объективный","беспристрастный"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'verisimilitude' mean?",opts:["правдоподобие","достоверность","похожесть","реализм"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"Which is correct: 'Little ___ he realise what awaited him'?",opts:["did","had","has","was"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"What does 'zeitgeist' mean?",opts:["дух времени","ход истории","современная культура","мировоззрение"],a:0,lv:"C2",xp:10,type:"choice"},
{q:"Translate to English: «теория познания»",a:"epistemology",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «говорить уклончиво»",a:"equivocate",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «усугублять»",a:"exacerbate",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «закоренелый»",a:"inveterate",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «лаконичный»",a:"laconic",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «лживый»",a:"mendacious",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «запутывать»",a:"obfuscate",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «кристально ясный»",a:"pellucid",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «непокорный»",a:"recalcitrant",lv:"C2",xp:12,type:"input"},
{q:"Translate to English: «подхалимский»",a:"sycophantic",lv:"C2",xp:12,type:"input"},
{q:"🎧 Listen and choose the correct word",word:"exacerbate",opts:["exacerbate","exaggerate","exasperate","accelerate"],lv:"C2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"inveterate",opts:["inveterate","invertebrate","intricate","inadequate"],lv:"C2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"mendacious",opts:["mendacious","tenacious","capacious","vivacious"],lv:"C2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"obfuscate",opts:["obfuscate","educate","eradicate","fabricate"],lv:"C2",xp:15,type:"listen"},
{q:"🎧 Listen and choose the correct word",word:"recalcitrant",opts:["recalcitrant","recalibrate","reintegrate","reciprocate"],lv:"C2",xp:15,type:"listen"},
"""
