SENTENCES = """
{en:"Can you help me?",ru:"Вы можете мне помочь?",lv:"A1",cat:"daily"},
{en:"Where is the toilet?",ru:"Где туалет?",lv:"A1",cat:"daily"},
{en:"I don't understand.",ru:"Я не понимаю.",lv:"A1",cat:"daily"},
{en:"Please speak slowly.",ru:"Пожалуйста, говорите медленнее.",lv:"A1",cat:"daily"},
{en:"My name is Anna.",ru:"Меня зовут Анна.",lv:"A1",cat:"daily"},
{en:"I am from Russia.",ru:"Я из России.",lv:"A1",cat:"daily"},
{en:"How much does it cost?",ru:"Сколько это стоит?",lv:"A1",cat:"shopping"},
{en:"Where is the bus stop?",ru:"Где автобусная остановка?",lv:"A1",cat:"transport"},
{en:"I need a doctor.",ru:"Мне нужен врач.",lv:"A1",cat:"medical"},
{en:"Call an ambulance, please.",ru:"Вызовите скорую помощь, пожалуйста.",lv:"A1",cat:"medical"},
{en:"Where is the hospital?",ru:"Где больница?",lv:"A1",cat:"medical"},
{en:"I have a headache.",ru:"У меня болит голова.",lv:"A1",cat:"medical"},
{en:"I am hungry.",ru:"Я голоден / Я голодна.",lv:"A1",cat:"food"},
{en:"I am thirsty.",ru:"Я хочу пить.",lv:"A1",cat:"food"},
{en:"Can I have the menu?",ru:"Можно мне меню?",lv:"A1",cat:"food"},
{en:"Water, please.",ru:"Воду, пожалуйста.",lv:"A1",cat:"food"},
{en:"The bill, please.",ru:"Счёт, пожалуйста.",lv:"A1",cat:"food"},
{en:"Where is the supermarket?",ru:"Где супермаркет?",lv:"A1",cat:"shopping"},
{en:"Do you have this in a bigger size?",ru:"У вас есть это в большем размере?",lv:"A1",cat:"shopping"},
{en:"I would like to buy this.",ru:"Я хотел бы это купить.",lv:"A1",cat:"shopping"},
{en:"Where is the airport?",ru:"Где аэропорт?",lv:"A1",cat:"transport"},
{en:"I need a taxi.",ru:"Мне нужно такси.",lv:"A1",cat:"transport"},
{en:"Take me to this address.",ru:"Отвезите меня по этому адресу.",lv:"A1",cat:"transport"},
{en:"How far is it?",ru:"Как далеко это?",lv:"A1",cat:"transport"},
{en:"I have a reservation.",ru:"У меня есть бронь.",lv:"A1",cat:"hotel"},
{en:"My name is on the booking.",ru:"Моё имя указано в бронировании.",lv:"A1",cat:"hotel"},
{en:"I need a room for one night.",ru:"Мне нужен номер на одну ночь.",lv:"A1",cat:"hotel"},
{en:"Where is my room?",ru:"Где мой номер?",lv:"A1",cat:"hotel"},
{en:"What time is check-out?",ru:"В какое время выезд?",lv:"A1",cat:"hotel"},
{en:"The key does not work.",ru:"Ключ не работает.",lv:"A1",cat:"hotel"},
{en:"I want to open a bank account.",ru:"Я хочу открыть банковский счёт.",lv:"A1",cat:"bank"},
{en:"Where is the ATM?",ru:"Где банкомат?",lv:"A1",cat:"bank"},
{en:"I need to change money.",ru:"Мне нужно обменять деньги.",lv:"A1",cat:"bank"},
{en:"Can I pay by card?",ru:"Можно оплатить картой?",lv:"A1",cat:"bank"},
{en:"Please call the police.",ru:"Пожалуйста, вызовите полицию.",lv:"A1",cat:"legal"},
{en:"I lost my passport.",ru:"Я потерял паспорт.",lv:"A1",cat:"legal"},
{en:"My bag was stolen.",ru:"У меня украли сумку.",lv:"A1",cat:"legal"},
{en:"I need a translator.",ru:"Мне нужен переводчик.",lv:"A1",cat:"legal"},
{en:"Where do I live? I live at this address.",ru:"Где я живу? Я живу по этому адресу.",lv:"A1",cat:"home"},
{en:"I need to rent a flat.",ru:"Мне нужно снять квартиру.",lv:"A1",cat:"home"},
{en:"Where is the nearest school?",ru:"Где ближайшая школа?",lv:"A1",cat:"study"},
{en:"I want to learn English.",ru:"Я хочу учить английский.",lv:"A1",cat:"study"},
{en:"Good morning.",ru:"Доброе утро.",lv:"A1",cat:"daily"},
{en:"Good evening.",ru:"Добрый вечер.",lv:"A1",cat:"daily"},
{en:"Thank you very much.",ru:"Большое спасибо.",lv:"A1",cat:"daily"},
{en:"You are welcome.",ru:"Пожалуйста / Не за что.",lv:"A1",cat:"daily"},
{en:"Excuse me.",ru:"Извините.",lv:"A1",cat:"daily"},
{en:"I am sorry.",ru:"Мне жаль / Извините.",lv:"A1",cat:"daily"},
{en:"Yes, please.",ru:"Да, пожалуйста.",lv:"A1",cat:"daily"},
{en:"No, thank you.",ru:"Нет, спасибо.",lv:"A1",cat:"daily"},
{en:"What is this?",ru:"Что это?",lv:"A1",cat:"daily"},
{en:"I do not speak English well.",ru:"Я не очень хорошо говорю по-английски.",lv:"A1",cat:"daily"},
{en:"Do you speak Russian?",ru:"Вы говорите по-русски?",lv:"A1",cat:"daily"},
{en:"Can you write it down?",ru:"Вы можете записать это?",lv:"A1",cat:"daily"},
{en:"Where is the exit?",ru:"Где выход?",lv:"A1",cat:"daily"},
{en:"How do I get to the city centre?",ru:"Как добраться до центра города?",lv:"A1",cat:"transport"},
{en:"I need a bus ticket.",ru:"Мне нужен билет на автобус.",lv:"A1",cat:"transport"},
{en:"Does this bus go to the station?",ru:"Этот автобус идёт до станции?",lv:"A1",cat:"transport"},
{en:"I missed my flight.",ru:"Я опоздал на самолёт.",lv:"A1",cat:"transport"},
{en:"Where is passport control?",ru:"Где паспортный контроль?",lv:"A1",cat:"transport"},
{en:"I have nothing to declare.",ru:"Мне нечего декларировать.",lv:"A1",cat:"transport"},
{en:"This is my luggage.",ru:"Это мой багаж.",lv:"A1",cat:"transport"},
{en:"I have a stomachache.",ru:"У меня болит живот.",lv:"A1",cat:"medical"},
{en:"I have a fever.",ru:"У меня температура.",lv:"A1",cat:"medical"},
{en:"I am allergic to penicillin.",ru:"У меня аллергия на пенициллин.",lv:"A1",cat:"medical"},
{en:"I need a prescription.",ru:"Мне нужен рецепт.",lv:"A1",cat:"medical"},
{en:"Where is the pharmacy?",ru:"Где аптека?",lv:"A1",cat:"medical"},
{en:"I need painkillers.",ru:"Мне нужны обезболивающие.",lv:"A1",cat:"medical"},
{en:"Where can I find a grocery store?",ru:"Где я могу найти продуктовый магазин?",lv:"A1",cat:"shopping"},
{en:"Is there a market nearby?",ru:"Есть ли рынок поблизости?",lv:"A1",cat:"shopping"},
{en:"Can I try this on?",ru:"Можно это примерить?",lv:"A1",cat:"shopping"},
{en:"Do you have a cheaper option?",ru:"Есть ли у вас более дешёвый вариант?",lv:"A1",cat:"shopping"},
{en:"I would like a receipt.",ru:"Я хотел бы получить чек.",lv:"A1",cat:"shopping"},
{en:"I work here.",ru:"Я здесь работаю.",lv:"A1",cat:"work"},
{en:"I am looking for a job.",ru:"Я ищу работу.",lv:"A1",cat:"work"},
{en:"Where is the office?",ru:"Где офис?",lv:"A1",cat:"work"},
{en:"What time does work start?",ru:"Во сколько начинается работа?",lv:"A1",cat:"work"},
{en:"I need to use the internet.",ru:"Мне нужно воспользоваться интернетом.",lv:"A1",cat:"misc"},
{en:"Where is the Wi-Fi password?",ru:"Где пароль от Wi-Fi?",lv:"A1",cat:"misc"},
{en:"I need to charge my phone.",ru:"Мне нужно зарядить телефон.",lv:"A1",cat:"misc"},
{en:"Can you repeat that?",ru:"Вы можете повторить?",lv:"A1",cat:"daily"},
{en:"I am lost.",ru:"Я заблудился / Я заблудилась.",lv:"A1",cat:"daily"},
{en:"Help!",ru:"Помогите!",lv:"A1",cat:"daily"},
{en:"Stop!",ru:"Стоп! / Остановитесь!",lv:"A1",cat:"daily"},
{en:"Is this the right way to the station?",ru:"Это правильный путь до станции?",lv:"A1",cat:"transport"},
{en:"I need a single room.",ru:"Мне нужен одноместный номер.",lv:"A1",cat:"hotel"},
{en:"Is breakfast included?",ru:"Завтрак включён?",lv:"A1",cat:"hotel"},
{en:"I need a towel.",ru:"Мне нужно полотенце.",lv:"A1",cat:"hotel"},
{en:"The room is too cold.",ru:"В номере слишком холодно.",lv:"A1",cat:"hotel"},
{en:"My name and surname, please.",ru:"Моё имя и фамилия, пожалуйста.",lv:"A1",cat:"daily"},
{en:"What is today's date?",ru:"Какое сегодня число?",lv:"A1",cat:"daily"},
{en:"What day is it today?",ru:"Какой сегодня день?",lv:"A1",cat:"daily"},
{en:"I need help with the form.",ru:"Мне нужна помощь с заполнением формы.",lv:"A1",cat:"misc"},
{en:"Where do I sign?",ru:"Где мне подписать?",lv:"A1",cat:"misc"},
{en:"I do not have cash.",ru:"У меня нет наличных.",lv:"A1",cat:"bank"},
{en:"I need a SIM card.",ru:"Мне нужна SIM-карта.",lv:"A1",cat:"misc"},
{en:"Where can I buy a bus pass?",ru:"Где можно купить проездной на автобус?",lv:"A1",cat:"transport"},
{en:"Can I speak to someone in Russian?",ru:"Могу ли я поговорить с кем-то по-русски?",lv:"A1",cat:"daily"},
{en:"I need a pen.",ru:"Мне нужна ручка.",lv:"A1",cat:"misc"},
{en:"Where is the post office?",ru:"Где почта?",lv:"A1",cat:"misc"},
{en:"Could you show me on the map?",ru:"Не могли бы вы показать мне на карте?",lv:"A2",cat:"daily"},
{en:"I would like to make an appointment.",ru:"Я хотел бы записаться на приём.",lv:"A2",cat:"medical"},
{en:"Is there a doctor who speaks Russian?",ru:"Есть ли врач, говорящий по-русски?",lv:"A2",cat:"medical"},
{en:"I need to register with a GP.",ru:"Мне нужно зарегистрироваться у терапевта.",lv:"A2",cat:"medical"},
{en:"Can I get a referral to a specialist?",ru:"Могу ли я получить направление к специалисту?",lv:"A2",cat:"medical"},
{en:"I have been feeling unwell for three days.",ru:"Я чувствую себя нехорошо уже три дня.",lv:"A2",cat:"medical"},
{en:"I take this medication every day.",ru:"Я принимаю это лекарство каждый день.",lv:"A2",cat:"medical"},
{en:"How often should I take these tablets?",ru:"Как часто мне нужно принимать эти таблетки?",lv:"A2",cat:"medical"},
{en:"I need to open a current account.",ru:"Мне нужно открыть текущий счёт.",lv:"A2",cat:"bank"},
{en:"What documents do I need to open an account?",ru:"Какие документы нужны для открытия счёта?",lv:"A2",cat:"bank"},
{en:"I would like to transfer money abroad.",ru:"Я хотел бы перевести деньги за рубеж.",lv:"A2",cat:"bank"},
{en:"My card has been blocked.",ru:"Моя карта заблокирована.",lv:"A2",cat:"bank"},
{en:"I forgot my PIN.",ru:"Я забыл PIN-код.",lv:"A2",cat:"bank"},
{en:"Can I get an account statement?",ru:"Могу ли я получить выписку по счёту?",lv:"A2",cat:"bank"},
{en:"What is the exchange rate today?",ru:"Какой сегодня обменный курс?",lv:"A2",cat:"bank"},
{en:"I need to pay rent by bank transfer.",ru:"Мне нужно оплатить аренду банковским переводом.",lv:"A2",cat:"bank"},
{en:"I am looking for a flat to rent.",ru:"Я ищу квартиру для аренды.",lv:"A2",cat:"home"},
{en:"How much is the monthly rent?",ru:"Сколько стоит аренда в месяц?",lv:"A2",cat:"home"},
{en:"Are bills included in the rent?",ru:"Коммунальные услуги включены в аренду?",lv:"A2",cat:"home"},
{en:"Is there a deposit?",ru:"Есть ли залог?",lv:"A2",cat:"home"},
{en:"When can I move in?",ru:"Когда я могу въехать?",lv:"A2",cat:"home"},
{en:"The heating is not working.",ru:"Отопление не работает.",lv:"A2",cat:"home"},
{en:"There is a leak in the bathroom.",ru:"В ванной течёт.",lv:"A2",cat:"home"},
{en:"Who is responsible for repairs?",ru:"Кто отвечает за ремонт?",lv:"A2",cat:"home"},
{en:"I would like to see the contract.",ru:"Я хотел бы ознакомиться с договором.",lv:"A2",cat:"home"},
{en:"I need to register my address.",ru:"Мне нужно зарегистрироваться по адресу.",lv:"A2",cat:"home"},
{en:"I would like to apply for this job.",ru:"Я хотел бы подать заявку на эту работу.",lv:"A2",cat:"work"},
{en:"Can I have a job application form?",ru:"Могу ли я получить бланк заявления о приёме на работу?",lv:"A2",cat:"work"},
{en:"I have experience in this field.",ru:"У меня есть опыт в этой области.",lv:"A2",cat:"work"},
{en:"When would I start?",ru:"Когда бы я начал работать?",lv:"A2",cat:"work"},
{en:"What are the working hours?",ru:"Каков рабочий график?",lv:"A2",cat:"work"},
{en:"Is there a probationary period?",ru:"Есть ли испытательный срок?",lv:"A2",cat:"work"},
{en:"What is the salary?",ru:"Какова зарплата?",lv:"A2",cat:"work"},
{en:"Do you offer sick pay?",ru:"Предоставляете ли вы оплату больничного?",lv:"A2",cat:"work"},
{en:"I need a national insurance number.",ru:"Мне нужен номер национального страхования.",lv:"A2",cat:"work"},
{en:"I would like to enrol my child in school.",ru:"Я хотел бы записать своего ребёнка в школу.",lv:"A2",cat:"study"},
{en:"What documents are needed for school enrolment?",ru:"Какие документы нужны для зачисления в школу?",lv:"A2",cat:"study"},
{en:"Are there English language classes for adults?",ru:"Есть ли курсы английского языка для взрослых?",lv:"A2",cat:"study"},
{en:"I need to improve my English.",ru:"Мне нужно улучшить свой английский.",lv:"A2",cat:"study"},
{en:"How do I register for a language course?",ru:"Как записаться на языковые курсы?",lv:"A2",cat:"study"},
{en:"Is there free English tuition available?",ru:"Доступно ли бесплатное обучение английскому?",lv:"A2",cat:"study"},
{en:"I would like a return ticket.",ru:"Я хотел бы билет туда и обратно.",lv:"A2",cat:"transport"},
{en:"Which platform does the train leave from?",ru:"С какой платформы отправляется поезд?",lv:"A2",cat:"transport"},
{en:"Is this seat taken?",ru:"Это место занято?",lv:"A2",cat:"transport"},
{en:"I need to validate my ticket.",ru:"Мне нужно прокомпостировать билет.",lv:"A2",cat:"transport"},
{en:"What time is the last bus?",ru:"Во сколько последний автобус?",lv:"A2",cat:"transport"},
{en:"How many stops until the city centre?",ru:"Сколько остановок до центра города?",lv:"A2",cat:"transport"},
{en:"I would like to hire a car.",ru:"Я хотел бы взять машину напрокат.",lv:"A2",cat:"transport"},
{en:"Is there a direct flight?",ru:"Есть ли прямой рейс?",lv:"A2",cat:"transport"},
{en:"My flight has been delayed.",ru:"Мой рейс задержан.",lv:"A2",cat:"transport"},
{en:"Where do I collect my luggage?",ru:"Где я могу получить свой багаж?",lv:"A2",cat:"transport"},
{en:"Can I have a non-smoking room, please?",ru:"Можно мне номер для некурящих, пожалуйста?",lv:"A2",cat:"hotel"},
{en:"I would like to extend my stay.",ru:"Я хотел бы продлить проживание.",lv:"A2",cat:"hotel"},
{en:"Is there a laundry service?",ru:"Есть ли услуга стирки?",lv:"A2",cat:"hotel"},
{en:"Can I store my luggage here?",ru:"Могу ли я оставить здесь свой багаж?",lv:"A2",cat:"hotel"},
{en:"The air conditioning is broken.",ru:"Кондиционер сломан.",lv:"A2",cat:"hotel"},
{en:"Could you bring extra pillows?",ru:"Не могли бы вы принести дополнительные подушки?",lv:"A2",cat:"hotel"},
{en:"Is there a gym in the hotel?",ru:"Есть ли в отеле тренажёрный зал?",lv:"A2",cat:"hotel"},
{en:"I would like to order room service.",ru:"Я хотел бы заказать обслуживание в номере.",lv:"A2",cat:"hotel"},
{en:"I am a vegetarian.",ru:"Я вегетарианец / Я вегетарианка.",lv:"A2",cat:"food"},
{en:"I am allergic to nuts.",ru:"У меня аллергия на орехи.",lv:"A2",cat:"food"},
{en:"What do you recommend?",ru:"Что вы рекомендуете?",lv:"A2",cat:"food"},
{en:"Is this dish spicy?",ru:"Это блюдо острое?",lv:"A2",cat:"food"},
{en:"I would like my steak well done.",ru:"Я хотел бы стейк хорошо прожаренный.",lv:"A2",cat:"food"},
{en:"Can I have a doggy bag?",ru:"Можно мне завернуть остатки с собой?",lv:"A2",cat:"food"},
{en:"There is a mistake on the bill.",ru:"В счёте есть ошибка.",lv:"A2",cat:"food"},
{en:"I would like to book a table for two.",ru:"Я хотел бы забронировать столик на двоих.",lv:"A2",cat:"food"},
{en:"I would like to make a complaint.",ru:"Я хотел бы подать жалобу.",lv:"A2",cat:"misc"},
{en:"I need to speak to the manager.",ru:"Мне нужно поговорить с менеджером.",lv:"A2",cat:"misc"},
{en:"Can you give me a written confirmation?",ru:"Вы можете дать мне письменное подтверждение?",lv:"A2",cat:"misc"},
{en:"I need this translated into English.",ru:"Мне нужно это перевести на английский.",lv:"A2",cat:"misc"},
{en:"Where is the nearest police station?",ru:"Где ближайший полицейский участок?",lv:"A2",cat:"legal"},
{en:"I need to report a theft.",ru:"Мне нужно сообщить о краже.",lv:"A2",cat:"legal"},
{en:"I need a police report for my insurance.",ru:"Мне нужен полицейский протокол для страховки.",lv:"A2",cat:"legal"},
{en:"I need to apply for a visa.",ru:"Мне нужно подать заявление на визу.",lv:"A2",cat:"legal"},
{en:"What documents do I need for registration?",ru:"Какие документы нужны для регистрации?",lv:"A2",cat:"legal"},
{en:"Can I speak to a solicitor?",ru:"Могу ли я поговорить с адвокатом?",lv:"A2",cat:"legal"},
{en:"I need to apply for benefits.",ru:"Мне нужно подать заявление на пособие.",lv:"A2",cat:"misc"},
{en:"Where is the social services office?",ru:"Где находится отдел социального обеспечения?",lv:"A2",cat:"misc"},
{en:"I have a young child and need support.",ru:"У меня маленький ребёнок, и мне нужна поддержка.",lv:"A2",cat:"misc"},
{en:"How do I get a library card?",ru:"Как мне получить читательский билет?",lv:"A2",cat:"study"},
{en:"I would like to use the computers at the library.",ru:"Я хотел бы воспользоваться компьютерами в библиотеке.",lv:"A2",cat:"study"},
{en:"Is there a children's play area nearby?",ru:"Есть ли поблизости детская игровая площадка?",lv:"A2",cat:"misc"},
{en:"Could you help me fill in this form?",ru:"Не могли бы вы помочь мне заполнить эту форму?",lv:"A2",cat:"misc"},
{en:"What are the opening hours?",ru:"Каков режим работы?",lv:"A2",cat:"misc"},
{en:"Is there a discount for students?",ru:"Есть ли скидка для студентов?",lv:"A2",cat:"shopping"},
{en:"I would like to return this item.",ru:"Я хотел бы вернуть этот товар.",lv:"A2",cat:"shopping"},
{en:"I have the receipt.",ru:"У меня есть чек.",lv:"A2",cat:"shopping"},
{en:"This item is damaged.",ru:"Этот товар повреждён.",lv:"A2",cat:"shopping"},
{en:"Do you have a loyalty card?",ru:"У вас есть карта лояльности?",lv:"A2",cat:"shopping"},
{en:"Can I pay in instalments?",ru:"Могу ли я оплатить в рассрочку?",lv:"A2",cat:"shopping"},
{en:"I need to set up a direct debit.",ru:"Мне нужно настроить прямое дебетование.",lv:"A2",cat:"bank"},
{en:"Can I speak to a customer service adviser?",ru:"Могу ли я поговорить с консультантом службы поддержки?",lv:"A2",cat:"bank"},
{en:"I need to update my personal details.",ru:"Мне нужно обновить свои личные данные.",lv:"A2",cat:"bank"},
{en:"How long does an international transfer take?",ru:"Сколько времени занимает международный перевод?",lv:"A2",cat:"bank"},
{en:"I need to apply for a work permit.",ru:"Мне нужно подать заявление на разрешение на работу.",lv:"B1",cat:"legal"},
{en:"Could you explain the terms of the contract?",ru:"Не могли бы вы объяснить условия договора?",lv:"B1",cat:"work"},
{en:"I would like to negotiate my salary.",ru:"Я хотел бы обсудить свою зарплату.",lv:"B1",cat:"work"},
{en:"I need to understand my employment rights.",ru:"Мне нужно понять свои трудовые права.",lv:"B1",cat:"work"},
{en:"Can I take annual leave in the first month?",ru:"Могу ли я взять ежегодный отпуск в первый месяц?",lv:"B1",cat:"work"},
{en:"I would like to discuss the performance review.",ru:"Я хотел бы обсудить оценку эффективности работы.",lv:"B1",cat:"work"},
{en:"I am having difficulty communicating with my colleagues.",ru:"У меня возникают трудности с общением с коллегами.",lv:"B1",cat:"work"},
{en:"I would like to request flexible working hours.",ru:"Я хотел бы попросить гибкий рабочий график.",lv:"B1",cat:"work"},
{en:"I need to give two weeks' notice.",ru:"Мне нужно предупредить за две недели.",lv:"B1",cat:"work"},
{en:"I have been unfairly dismissed.",ru:"Меня несправедливо уволили.",lv:"B1",cat:"work"},
{en:"I need to raise a grievance.",ru:"Мне нужно подать жалобу.",lv:"B1",cat:"work"},
{en:"Could you provide a reference letter?",ru:"Не могли бы вы предоставить рекомендательное письмо?",lv:"B1",cat:"work"},
{en:"I would like to apply for a promotion.",ru:"Я хотел бы претендовать на повышение.",lv:"B1",cat:"work"},
{en:"I need to attend a mandatory training session.",ru:"Мне нужно посетить обязательный тренинг.",lv:"B1",cat:"work"},
{en:"Can you explain the health and safety rules?",ru:"Не могли бы вы объяснить правила охраны труда?",lv:"B1",cat:"work"},
{en:"I would like to dispute this charge on my bank statement.",ru:"Я хотел бы оспорить эту операцию в банковской выписке.",lv:"B1",cat:"bank"},
{en:"I need to apply for a mortgage.",ru:"Мне нужно подать заявление на ипотеку.",lv:"B1",cat:"bank"},
{en:"What is the interest rate on this loan?",ru:"Какова процентная ставка по этому займу?",lv:"B1",cat:"bank"},
{en:"I would like to set up a savings account.",ru:"Я хотел бы открыть сберегательный счёт.",lv:"B1",cat:"bank"},
{en:"I think I have been charged incorrectly.",ru:"Мне кажется, с меня сняли неправильную сумму.",lv:"B1",cat:"bank"},
{en:"Can I get a credit card?",ru:"Могу ли я получить кредитную карту?",lv:"B1",cat:"bank"},
{en:"What are the fees for this account?",ru:"Каковы комиссии по этому счёту?",lv:"B1",cat:"bank"},
{en:"I need to arrange a standing order.",ru:"Мне нужно оформить регулярный платёж.",lv:"B1",cat:"bank"},
{en:"I would like to speak to a financial adviser.",ru:"Я хотел бы поговорить с финансовым консультантом.",lv:"B1",cat:"bank"},
{en:"I need to understand my tax obligations.",ru:"Мне нужно понять свои налоговые обязательства.",lv:"B1",cat:"bank"},
{en:"I need to register for self-assessment tax.",ru:"Мне нужно зарегистрироваться для самостоятельного налогового декларирования.",lv:"B1",cat:"bank"},
{en:"I have a problem with my landlord and need advice.",ru:"У меня проблема с арендодателем, и мне нужен совет.",lv:"B1",cat:"home"},
{en:"The landlord has not returned my deposit.",ru:"Арендодатель не вернул мой залог.",lv:"B1",cat:"home"},
{en:"The property is not in the condition described.",ru:"Имущество не в том состоянии, как было описано.",lv:"B1",cat:"home"},
{en:"I want to challenge an unfair clause in the tenancy agreement.",ru:"Я хочу оспорить несправедливый пункт договора аренды.",lv:"B1",cat:"home"},
{en:"How much notice must the landlord give before entering?",ru:"За какой срок арендодатель обязан предупредить о визите?",lv:"B1",cat:"home"},
{en:"The neighbours are causing a noise nuisance.",ru:"Соседи создают шумовые помехи.",lv:"B1",cat:"home"},
{en:"I need to apply for social housing.",ru:"Мне нужно подать заявление на социальное жильё.",lv:"B1",cat:"home"},
{en:"Can I sublet part of the property?",ru:"Могу ли я сдать в субаренду часть жилья?",lv:"B1",cat:"home"},
{en:"I would like a full check of the property inventory.",ru:"Я хотел бы провести полную проверку инвентарной описи.",lv:"B1",cat:"home"},
{en:"The contract says I must give one month's notice.",ru:"В договоре сказано, что я должен предупредить за один месяц.",lv:"B1",cat:"home"},
{en:"I would like to enrol on a college course.",ru:"Я хотел бы записаться на курсы в колледж.",lv:"B1",cat:"study"},
{en:"I need to get my qualifications recognised here.",ru:"Мне нужно получить признание моей квалификации здесь.",lv:"B1",cat:"study"},
{en:"Where can I take an English proficiency test?",ru:"Где я могу сдать тест на знание английского языка?",lv:"B1",cat:"study"},
{en:"I need to apply for a student loan.",ru:"Мне нужно подать заявление на студенческий кредит.",lv:"B1",cat:"study"},
{en:"Is there a scholarship available for international students?",ru:"Есть ли стипендия для иностранных студентов?",lv:"B1",cat:"study"},
{en:"I need a letter confirming my enrollment.",ru:"Мне нужно письмо, подтверждающее моё зачисление.",lv:"B1",cat:"study"},
{en:"Could you recommend a good language school?",ru:"Не могли бы вы порекомендовать хорошую языковую школу?",lv:"B1",cat:"study"},
{en:"I would like to speak to the school counsellor.",ru:"Я хотел бы поговорить со школьным консультантом.",lv:"B1",cat:"study"},
{en:"My child is struggling to adapt to the new school.",ru:"Мой ребёнок с трудом адаптируется в новой школе.",lv:"B1",cat:"study"},
{en:"I have a chronic condition and need regular monitoring.",ru:"У меня хроническое заболевание, и мне нужен регулярный контроль.",lv:"B1",cat:"medical"},
{en:"I need a referral to a mental health service.",ru:"Мне нужно направление в службу психического здоровья.",lv:"B1",cat:"medical"},
{en:"I would like a second opinion.",ru:"Я хотел бы получить второе мнение.",lv:"B1",cat:"medical"},
{en:"I need to know my rights as a patient.",ru:"Мне нужно знать свои права как пациента.",lv:"B1",cat:"medical"},
{en:"Can the results be explained in simple terms?",ru:"Могут ли результаты быть объяснены простыми словами?",lv:"B1",cat:"medical"},
{en:"I would like a female doctor, please.",ru:"Я хотела бы попасть к врачу-женщине, пожалуйста.",lv:"B1",cat:"medical"},
{en:"I need a sick note for my employer.",ru:"Мне нужен больничный лист для работодателя.",lv:"B1",cat:"medical"},
{en:"I have been experiencing these symptoms for two weeks.",ru:"Эти симптомы у меня наблюдаются уже две недели.",lv:"B1",cat:"medical"},
{en:"I need to understand the side effects of this medication.",ru:"Мне нужно понять побочные эффекты этого лекарства.",lv:"B1",cat:"medical"},
{en:"I would like to register as a dental patient.",ru:"Я хотел бы зарегистрироваться у стоматолога.",lv:"B1",cat:"medical"},
{en:"I need an emergency dental appointment.",ru:"Мне нужна срочная стоматологическая консультация.",lv:"B1",cat:"medical"},
{en:"I was involved in a road traffic accident.",ru:"Я попал в дорожно-транспортное происшествие.",lv:"B1",cat:"legal"},
{en:"I need to make a statement to the police.",ru:"Мне нужно дать показания полиции.",lv:"B1",cat:"legal"},
{en:"I believe I am a victim of discrimination.",ru:"Я считаю, что стал жертвой дискриминации.",lv:"B1",cat:"legal"},
{en:"I need legal aid.",ru:"Мне нужна юридическая помощь.",lv:"B1",cat:"legal"},
{en:"What are my rights if I am stopped by the police?",ru:"Каковы мои права, если меня остановит полиция?",lv:"B1",cat:"legal"},
{en:"I need to apply for permanent residency.",ru:"Мне нужно подать заявление на постоянное место жительства.",lv:"B1",cat:"legal"},
{en:"Can I appeal against this decision?",ru:"Могу ли я обжаловать это решение?",lv:"B1",cat:"legal"},
{en:"I would like to get married here — what is the process?",ru:"Я хотел бы пожениться здесь — какова процедура?",lv:"B1",cat:"legal"},
{en:"I need to obtain a certified copy of a document.",ru:"Мне нужно получить заверенную копию документа.",lv:"B1",cat:"legal"},
{en:"I received a fine and want to contest it.",ru:"Я получил штраф и хочу его оспорить.",lv:"B1",cat:"legal"},
{en:"I need to arrange car insurance.",ru:"Мне нужно оформить страховку на автомобиль.",lv:"B1",cat:"misc"},
{en:"What does the insurance policy cover?",ru:"Что покрывает страховой полис?",lv:"B1",cat:"misc"},
{en:"I need to file an insurance claim.",ru:"Мне нужно подать страховое заявление.",lv:"B1",cat:"misc"},
{en:"I would like to compare utility tariffs.",ru:"Я хотел бы сравнить тарифы на коммунальные услуги.",lv:"B1",cat:"home"},
{en:"How do I set up electricity and gas in my name?",ru:"Как переоформить электричество и газ на своё имя?",lv:"B1",cat:"home"},
{en:"I would like to complain about the service I received.",ru:"Я хотел бы пожаловаться на обслуживание, которое я получил.",lv:"B1",cat:"misc"},
{en:"Can I speak to the duty manager?",ru:"Могу ли я поговорить с дежурным менеджером?",lv:"B1",cat:"misc"},
{en:"I need to understand the cancellation policy.",ru:"Мне нужно понять политику отмены.",lv:"B1",cat:"misc"},
{en:"I would like a full refund.",ru:"Я хотел бы полный возврат средств.",lv:"B1",cat:"shopping"},
{en:"Under consumer law, I am entitled to a replacement.",ru:"По закону о защите прав потребителей мне полагается замена.",lv:"B1",cat:"shopping"},
{en:"I need to file a small claims court application.",ru:"Мне нужно подать заявление в суд по мелким претензиям.",lv:"B1",cat:"legal"},
{en:"My employer has not paid my wages.",ru:"Работодатель не выплатил мне зарплату.",lv:"B1",cat:"work"},
{en:"I would like to join a trade union.",ru:"Я хотел бы вступить в профсоюз.",lv:"B1",cat:"work"},
{en:"Can you explain the redundancy process?",ru:"Не могли бы вы объяснить процедуру сокращения?",lv:"B1",cat:"work"},
{en:"I need to set up a business bank account.",ru:"Мне нужно открыть расчётный счёт для бизнеса.",lv:"B1",cat:"bank"},
{en:"I would like to register as self-employed.",ru:"Я хотел бы зарегистрироваться как самозанятый.",lv:"B1",cat:"work"},
{en:"Can I use this address as my registered office?",ru:"Могу ли я использовать этот адрес в качестве юридического адреса?",lv:"B1",cat:"work"},
{en:"I need to obtain a council tax exemption.",ru:"Мне нужно получить освобождение от муниципального налога.",lv:"B1",cat:"home"},
{en:"I believe I qualify for a council tax reduction.",ru:"Я считаю, что имею право на снижение муниципального налога.",lv:"B1",cat:"home"},
{en:"I would like to know about public transport season tickets.",ru:"Я хотел бы узнать о сезонных проездных на общественный транспорт.",lv:"B1",cat:"transport"},
{en:"I need to notify the DVLA of my change of address.",ru:"Мне нужно уведомить DVLA об изменении адреса.",lv:"B1",cat:"transport"},
{en:"I would like to take a driving test.",ru:"Я хотел бы сдать экзамен по вождению.",lv:"B1",cat:"transport"},
{en:"Is my foreign driving licence valid here?",ru:"Действительно ли моё иностранное водительское удостоверение здесь?",lv:"B1",cat:"transport"},
{en:"I need to exchange my foreign driving licence.",ru:"Мне нужно обменять иностранное водительское удостоверение.",lv:"B1",cat:"transport"},
{en:"I would like to dispute the terms of my rental agreement.",ru:"Я хотел бы оспорить условия договора аренды.",lv:"B2",cat:"home"},
{en:"I am writing to formally notify you of a maintenance issue.",ru:"Я пишу, чтобы официально уведомить вас о проблеме с техническим обслуживанием.",lv:"B2",cat:"home"},
{en:"Please provide written confirmation of the agreed repairs.",ru:"Пожалуйста, предоставьте письменное подтверждение согласованных ремонтных работ.",lv:"B2",cat:"home"},
{en:"I wish to serve notice to terminate my tenancy.",ru:"Я хочу направить уведомление о расторжении договора аренды.",lv:"B2",cat:"home"},
{en:"I believe the eviction notice is not legally valid.",ru:"Я считаю, что уведомление о выселении не является юридически действительным.",lv:"B2",cat:"home"},
{en:"I need to escalate this matter to the housing ombudsman.",ru:"Мне нужно передать этот вопрос в жилищный омбудсмен.",lv:"B2",cat:"home"},
{en:"I would like to formally request a rent review.",ru:"Я хотел бы официально запросить пересмотр арендной платы.",lv:"B2",cat:"home"},
{en:"The property has not been maintained to a habitable standard.",ru:"Жильё не поддерживается в пригодном для жизни состоянии.",lv:"B2",cat:"home"},
{en:"I am pursuing the return of my deposit through the tenancy deposit scheme.",ru:"Я добиваюсь возврата залога через схему депонирования арендных залогов.",lv:"B2",cat:"home"},
{en:"I would like to apply for planning permission for an extension.",ru:"Я хотел бы подать заявление на получение разрешения на пристройку.",lv:"B2",cat:"home"},
{en:"I would like to understand the implications of this clause.",ru:"Я хотел бы понять последствия этого пункта.",lv:"B2",cat:"legal"},
{en:"I am seeking legal representation in this matter.",ru:"Я ищу юридическое представительство в этом вопросе.",lv:"B2",cat:"legal"},
{en:"I wish to appeal against the decision on the grounds of procedural irregularity.",ru:"Я хочу обжаловать решение на основании процессуального нарушения.",lv:"B2",cat:"legal"},
{en:"I need to understand the scope of data protection rights.",ru:"Мне нужно понять объём прав на защиту персональных данных.",lv:"B2",cat:"legal"},
{en:"I wish to make a subject access request.",ru:"Я хочу подать запрос на доступ к персональным данным.",lv:"B2",cat:"legal"},
{en:"I believe my human rights have been violated.",ru:"Я считаю, что мои права человека были нарушены.",lv:"B2",cat:"legal"},
{en:"I need to apply for citizenship.",ru:"Мне нужно подать заявление на получение гражданства.",lv:"B2",cat:"legal"},
{en:"I would like to contest the terms of this settlement.",ru:"Я хотел бы оспорить условия этого урегулирования.",lv:"B2",cat:"legal"},
{en:"Under the Equality Act, I am protected from this treatment.",ru:"В соответствии с Законом о равенстве я защищён от такого обращения.",lv:"B2",cat:"legal"},
{en:"I need to obtain a court order.",ru:"Мне нужно получить судебный приказ.",lv:"B2",cat:"legal"},
{en:"I wish to negotiate a settlement without going to court.",ru:"Я хочу урегулировать вопрос без судебного разбирательства.",lv:"B2",cat:"legal"},
{en:"I need to understand the implications of declaring bankruptcy.",ru:"Мне нужно понять последствия объявления о банкротстве.",lv:"B2",cat:"bank"},
{en:"I would like to dispute a default on my credit file.",ru:"Я хотел бы оспорить неоплаченный долг в моей кредитной истории.",lv:"B2",cat:"bank"},
{en:"I need to set up a trust fund.",ru:"Мне нужно учредить трастовый фонд.",lv:"B2",cat:"bank"},
{en:"I would like to review the terms of my mortgage.",ru:"Я хотел бы пересмотреть условия ипотеки.",lv:"B2",cat:"bank"},
{en:"I need to formally dispute this transaction.",ru:"Мне нужно официально оспорить эту транзакцию.",lv:"B2",cat:"bank"},
{en:"I would like to understand capital gains tax implications.",ru:"Я хотел бы понять последствия налога на прирост капитала.",lv:"B2",cat:"bank"},
{en:"I am submitting my annual self-assessment tax return.",ru:"Я подаю ежегодную налоговую декларацию.",lv:"B2",cat:"bank"},
{en:"I need to declare overseas income to HMRC.",ru:"Мне нужно задекларировать доход из-за рубежа в HMRC.",lv:"B2",cat:"bank"},
{en:"I am writing to formally request a payment plan.",ru:"Я пишу с официальным запросом о плане погашения задолженности.",lv:"B2",cat:"bank"},
{en:"I need to register for VAT.",ru:"Мне нужно зарегистрироваться в качестве плательщика НДС.",lv:"B2",cat:"bank"},
{en:"I would like to formally raise a grievance under company policy.",ru:"Я хотел бы официально подать жалобу в соответствии с политикой компании.",lv:"B2",cat:"work"},
{en:"I believe I have been constructively dismissed.",ru:"Я считаю, что меня вынудили уволиться.",lv:"B2",cat:"work"},
{en:"I wish to refer this matter to an employment tribunal.",ru:"Я хочу передать этот вопрос в трудовой трибунал.",lv:"B2",cat:"work"},
{en:"I am requesting reasonable adjustments under the Equality Act.",ru:"Я прошу разумных корректировок в соответствии с Законом о равенстве.",lv:"B2",cat:"work"},
{en:"I need to understand my rights regarding maternity pay.",ru:"Мне нужно разобраться в своих правах на декретные выплаты.",lv:"B2",cat:"work"},
{en:"I would like to request a flexible working arrangement formally.",ru:"Я хотел бы официально запросить гибкий режим работы.",lv:"B2",cat:"work"},
{en:"The company has breached the terms of my employment contract.",ru:"Компания нарушила условия моего трудового договора.",lv:"B2",cat:"work"},
{en:"I need to provide evidence of my professional qualifications.",ru:"Мне нужно предоставить доказательства своей профессиональной квалификации.",lv:"B2",cat:"work"},
{en:"I wish to apply for an enhanced DBS check.",ru:"Я хочу подать заявку на расширенную проверку биографических данных (DBS).",lv:"B2",cat:"work"},
{en:"I would like to discuss the terms of my redundancy package.",ru:"Я хотел бы обсудить условия моего выходного пособия.",lv:"B2",cat:"work"},
{en:"I need to obtain accreditation for my overseas degree.",ru:"Мне нужно получить аккредитацию для моей зарубежной степени.",lv:"B2",cat:"study"},
{en:"I would like to enrol on a professional development course.",ru:"Я хотел бы записаться на курс профессионального развития.",lv:"B2",cat:"study"},
{en:"I am applying to university and need a personal statement.",ru:"Я поступаю в университет и мне нужно личное заявление.",lv:"B2",cat:"study"},
{en:"I need to provide proof of English language proficiency.",ru:"Мне нужно подтвердить уровень владения английским языком.",lv:"B2",cat:"study"},
{en:"I would like to audit a course before committing to enrolment.",ru:"Я хотел бы посетить курс в качестве вольнослушателя перед зачислением.",lv:"B2",cat:"study"},
{en:"I would like to request a reasonable adjustment for my exam.",ru:"Я хотел бы запросить разумную корректировку для моего экзамена.",lv:"B2",cat:"study"},
{en:"I am enquiring about postgraduate research opportunities.",ru:"Я интересуюсь возможностями для аспирантских исследований.",lv:"B2",cat:"study"},
{en:"I believe my diagnosis has not been adequately explained to me.",ru:"Я считаю, что мой диагноз не был мне достаточно разъяснён.",lv:"B2",cat:"medical"},
{en:"I would like to make a formal complaint about my care.",ru:"Я хотел бы подать официальную жалобу на своё лечение.",lv:"B2",cat:"medical"},
{en:"I need to be referred to an NHS specialist urgently.",ru:"Мне срочно нужно направление к специалисту NHS.",lv:"B2",cat:"medical"},
{en:"I need to ensure my medical records are transferred.",ru:"Мне нужно обеспечить передачу моих медицинских записей.",lv:"B2",cat:"medical"},
{en:"I am seeking a private consultation for a second opinion.",ru:"Я ищу частную консультацию для получения второго мнения.",lv:"B2",cat:"medical"},
{en:"I need to understand the risks and benefits of this procedure.",ru:"Мне нужно понять риски и пользу этой процедуры.",lv:"B2",cat:"medical"},
{en:"I withdraw my consent to this treatment.",ru:"Я отзываю своё согласие на это лечение.",lv:"B2",cat:"medical"},
{en:"I would like a detailed explanation of my treatment plan.",ru:"Я хотел бы подробное объяснение моего плана лечения.",lv:"B2",cat:"medical"},
{en:"I am enquiring about elective surgery options.",ru:"Я интересуюсь вариантами плановой хирургии.",lv:"B2",cat:"medical"},
{en:"I have been waiting over the target time for my appointment.",ru:"Я ждал своей записи дольше установленного срока.",lv:"B2",cat:"medical"},
{en:"I need to renew my residence permit.",ru:"Мне нужно продлить вид на жительство.",lv:"B2",cat:"legal"},
{en:"I would like to appeal the decision on my visa application.",ru:"Я хотел бы обжаловать решение по моей визовой заявке.",lv:"B2",cat:"legal"},
{en:"I am submitting evidence in support of my asylum claim.",ru:"Я представляю доказательства в поддержку моего ходатайства об убежище.",lv:"B2",cat:"legal"},
{en:"I need to change my immigration status.",ru:"Мне нужно изменить свой иммиграционный статус.",lv:"B2",cat:"legal"},
{en:"I would like to understand the conditions of my leave to remain.",ru:"Я хотел бы понять условия моего разрешения на пребывание.",lv:"B2",cat:"legal"},
{en:"I am writing to formally object to planning permission for this development.",ru:"Я пишу, чтобы официально выразить возражение против разрешения на строительство этого объекта.",lv:"B2",cat:"legal"},
{en:"I need an interpreter for court proceedings.",ru:"Мне нужен переводчик для судебного заседания.",lv:"B2",cat:"legal"},
{en:"I would like to make a power of attorney.",ru:"Я хотел бы оформить доверенность.",lv:"B2",cat:"legal"},
{en:"I need to instruct a solicitor to review this agreement.",ru:"Мне нужно поручить адвокату проверить это соглашение.",lv:"B2",cat:"legal"},
{en:"I wish to contest the terms of a will.",ru:"Я хочу оспорить условия завещания.",lv:"B2",cat:"legal"},
{en:"I would like to make a formal complaint to the ombudsman.",ru:"Я хотел бы подать официальную жалобу омбудсмену.",lv:"B2",cat:"misc"},
{en:"I am requesting a subject access report under GDPR.",ru:"Я запрашиваю отчёт о персональных данных в соответствии с GDPR.",lv:"B2",cat:"misc"},
{en:"I need to set up a limited company.",ru:"Мне нужно учредить компанию с ограниченной ответственностью.",lv:"B2",cat:"work"},
{en:"I need to file my company's annual return.",ru:"Мне нужно подать ежегодный отчёт компании.",lv:"B2",cat:"work"},
{en:"I would like to tender my resignation in writing.",ru:"Я хотел бы подать заявление об увольнении в письменной форме.",lv:"B2",cat:"work"},
{en:"I am writing to express my dissatisfaction with the level of service.",ru:"Я пишу, чтобы выразить своё недовольство уровнем обслуживания.",lv:"B2",cat:"misc"},
{en:"I wish to renegotiate the terms of this commercial agreement.",ru:"Я хочу пересмотреть условия данного коммерческого соглашения.",lv:"C1",cat:"work"},
{en:"The contractual obligations have not been fulfilled as agreed.",ru:"Договорные обязательства не были выполнены в соответствии с договорённостью.",lv:"C1",cat:"work"},
{en:"I am seeking damages for breach of contract.",ru:"Я требую возмещения ущерба за нарушение договора.",lv:"C1",cat:"legal"},
{en:"I would like to invoke the dispute resolution clause.",ru:"Я хотел бы применить положение о разрешении споров.",lv:"C1",cat:"legal"},
{en:"The liability waiver does not cover circumstances of gross negligence.",ru:"Отказ от ответственности не распространяется на случаи грубой небрежности.",lv:"C1",cat:"legal"},
{en:"I need to understand the jurisdictional basis of this claim.",ru:"Мне нужно разобраться в юрисдикционной основе данного иска.",lv:"C1",cat:"legal"},
{en:"I am challenging the proportionality of this penalty.",ru:"Я оспариваю соразмерность данного штрафа.",lv:"C1",cat:"legal"},
{en:"I need legal counsel specialising in immigration law.",ru:"Мне нужен юрист, специализирующийся в области иммиграционного права.",lv:"C1",cat:"legal"},
{en:"I wish to seek judicial review of the administrative decision.",ru:"Я хочу добиться судебного контроля за административным решением.",lv:"C1",cat:"legal"},
{en:"I need to understand the ramifications of this indemnity clause.",ru:"Мне нужно понять последствия данного положения об освобождении от ответственности.",lv:"C1",cat:"legal"},
{en:"I am requesting a without-prejudice meeting to resolve this dispute.",ru:"Я прошу провести встречу без ущерба для дела в суде, чтобы урегулировать этот спор.",lv:"C1",cat:"legal"},
{en:"My credit file contains inaccurate information that I wish to have rectified.",ru:"В моей кредитной истории содержится неверная информация, которую я хочу исправить.",lv:"C1",cat:"bank"},
{en:"I need to restructure my debt obligations through a formal arrangement.",ru:"Мне нужно реструктурировать свои долговые обязательства посредством официального соглашения.",lv:"C1",cat:"bank"},
{en:"I would like to explore offshore tax-efficient investment options.",ru:"Я хотел бы изучить офшорные налогово-эффективные инвестиционные возможности.",lv:"C1",cat:"bank"},
{en:"I need to understand the implications of a deed of variation.",ru:"Мне нужно понять последствия акта изменения условий завещания.",lv:"C1",cat:"legal"},
{en:"I am seeking to bring a class action lawsuit.",ru:"Я стремлюсь подать коллективный иск.",lv:"C1",cat:"legal"},
{en:"I would like to understand my rights under the Human Rights Act.",ru:"Я хотел бы понять свои права в соответствии с Законом о правах человека.",lv:"C1",cat:"legal"},
{en:"I wish to register a beneficial interest in the property.",ru:"Я хочу зарегистрировать выгодный интерес в отношении данного имущества.",lv:"C1",cat:"home"},
{en:"I need to apply for a leasehold extension.",ru:"Мне нужно подать заявление на продление аренды.",lv:"C1",cat:"home"},
{en:"I am in the process of conducting due diligence on this acquisition.",ru:"Я провожу процедуру комплексной проверки данного приобретения.",lv:"C1",cat:"work"},
{en:"I need to draft a shareholder agreement.",ru:"Мне нужно составить акционерное соглашение.",lv:"C1",cat:"work"},
{en:"I would like to raise concerns about corporate governance.",ru:"Я хотел бы выразить обеспокоенность корпоративным управлением.",lv:"C1",cat:"work"},
{en:"I am requesting a formal capability procedure rather than a disciplinary one.",ru:"Я прошу о проведении официальной процедуры оценки профессиональной пригодности, а не дисциплинарной.",lv:"C1",cat:"work"},
{en:"The whistleblowing policy protects me from retaliation in this case.",ru:"Политика защиты информаторов защищает меня от репрессий в данном случае.",lv:"C1",cat:"work"},
{en:"I am raising a protected disclosure under the Public Interest Disclosure Act.",ru:"Я делаю защищённое раскрытие в соответствии с Законом о публичном раскрытии информации.",lv:"C1",cat:"work"},
{en:"I need to assess my eligibility for indefinite leave to remain.",ru:"Мне нужно оценить своё право на бессрочное разрешение на пребывание.",lv:"C1",cat:"legal"},
{en:"I wish to apply for naturalisation as a British citizen.",ru:"Я хочу подать заявление на натурализацию в качестве гражданина Великобритании.",lv:"C1",cat:"legal"},
{en:"I need expert testimony to support my medical negligence claim.",ru:"Мне нужны экспертные показания для подтверждения моего иска о медицинской халатности.",lv:"C1",cat:"medical"},
{en:"I want to discuss the ethical implications of the recommended treatment.",ru:"Я хочу обсудить этические последствия рекомендованного лечения.",lv:"C1",cat:"medical"},
{en:"I am requesting a multidisciplinary team meeting to review my case.",ru:"Я прошу организовать заседание мультидисциплинарной команды для рассмотрения моего случая.",lv:"C1",cat:"medical"},
{en:"I need to access my complete medical records under data protection law.",ru:"Мне нужно получить доступ к своим полным медицинским записям в соответствии с законом о защите данных.",lv:"C1",cat:"medical"},
{en:"I wish to make an advance decision regarding my medical care.",ru:"Я хочу принять заблаговременное решение относительно моего медицинского обслуживания.",lv:"C1",cat:"medical"},
{en:"I need to understand the prognosis and long-term treatment pathway.",ru:"Мне нужно понять прогноз и долгосрочный путь лечения.",lv:"C1",cat:"medical"},
{en:"I am concerned about potential conflicts of interest in this organisation.",ru:"Меня беспокоят возможные конфликты интересов в этой организации.",lv:"C1",cat:"misc"},
{en:"I would like to formally escalate my concerns to the board of directors.",ru:"Я хотел бы официально довести свои опасения до совета директоров.",lv:"C1",cat:"misc"},
{en:"I need to negotiate a favourable settlement before the case proceeds to trial.",ru:"Мне нужно договориться о выгодном урегулировании до передачи дела в суд.",lv:"C1",cat:"legal"},
{en:"I would like to understand my rights under the Freedom of Information Act.",ru:"Я хотел бы понять свои права в соответствии с Законом о свободе информации.",lv:"C1",cat:"legal"},
{en:"I need to apply for a statutory declaration.",ru:"Мне нужно подать заявление на официальное заявление под присягой.",lv:"C1",cat:"legal"},
{en:"The indemnification provisions in this agreement are overly broad.",ru:"Положения о возмещении ущерба в данном соглашении чрезмерно широки.",lv:"C2",cat:"legal"},
{en:"I am challenging the lawfulness of the detention on habeas corpus grounds.",ru:"Я оспариваю законность задержания на основании habeas corpus.",lv:"C2",cat:"legal"},
{en:"The doctrine of promissory estoppel may be applicable to this situation.",ru:"Принцип estoppel обещания может быть применим к данной ситуации.",lv:"C2",cat:"legal"},
{en:"I am seeking an injunction to restrain the respondent from further action.",ru:"Я добиваюсь судебного запрета, ограничивающего ответчика от дальнейших действий.",lv:"C2",cat:"legal"},
{en:"The force majeure clause was not properly invoked under the circumstances.",ru:"Положение о форс-мажоре не было должным образом применено при данных обстоятельствах.",lv:"C2",cat:"legal"},
{en:"I am asserting my rights under the doctrine of legitimate expectation.",ru:"Я отстаиваю свои права на основании доктрины правомерных ожиданий.",lv:"C2",cat:"legal"},
{en:"I need to understand the interplay between domestic legislation and treaty obligations.",ru:"Мне нужно понять взаимодействие внутреннего законодательства и договорных обязательств.",lv:"C2",cat:"legal"},
{en:"The decision is susceptible to judicial review on the grounds of irrationality.",ru:"Решение может быть пересмотрено в судебном порядке по основаниям нерациональности.",lv:"C2",cat:"legal"},
{en:"I need to instruct leading counsel on this constitutional matter.",ru:"Мне нужно поручить ведущему юристу ведение этого конституционного дела.",lv:"C2",cat:"legal"},
{en:"I wish to submit an amicus curiae brief to assist the court.",ru:"Я хочу представить заключение amicus curiae для помощи суду.",lv:"C2",cat:"legal"},
{en:"The risk-adjusted return profile of this portfolio requires careful scrutiny.",ru:"Профиль доходности данного портфеля с учётом риска требует тщательного анализа.",lv:"C2",cat:"bank"},
{en:"I am querying the basis on which the transfer pricing has been calculated.",ru:"Я ставлю под сомнение основу расчёта трансфертных цен.",lv:"C2",cat:"bank"},
{en:"I need to negotiate the covenants attached to this commercial lending facility.",ru:"Мне нужно согласовать ковенанты, прилагаемые к данной коммерческой кредитной линии.",lv:"C2",cat:"bank"},
{en:"The fiduciary obligations of the trustee have been demonstrably breached.",ru:"Доверительные обязательства управляющего были явно нарушены.",lv:"C2",cat:"bank"},
{en:"I wish to explore the tax treaty provisions applicable to my residency status.",ru:"Я хочу изучить положения налогового договора, применимые к моему статусу резидентства.",lv:"C2",cat:"bank"},
{en:"The vicarious liability of the employer is clearly established on these facts.",ru:"Ответственность работодателя за действия работника явно установлена на основании данных фактов.",lv:"C2",cat:"work"},
{en:"I am challenging the proportionality of the disciplinary sanction imposed.",ru:"Я оспариваю соразмерность наложенного дисциплинарного взыскания.",lv:"C2",cat:"work"},
{en:"The restrictive covenant post-termination is unenforceable as drafted.",ru:"Ограничительный ковенант после прекращения трудовых отношений в его нынешней редакции не имеет исковой силы.",lv:"C2",cat:"work"},
{en:"I am making a protected disclosure under the whistleblowing legislation.",ru:"Я осуществляю защищённое раскрытие информации в соответствии с законодательством о защите информаторов.",lv:"C2",cat:"work"},
{en:"The constructive dismissal claim turns on whether the conduct was repudiatory.",ru:"Иск о принудительном увольнении зависит от того, носило ли поведение характер отказа от договора.",lv:"C2",cat:"work"},
"""
