WORDS_A1_A2 = """
{en:"hello",ph:"həˈləʊ",ru:"привет / здравствуйте",ex:"Hello, how are you today?",lv:"A1",cat:"daily"},
{en:"goodbye",ph:"ɡʊdˈbaɪ",ru:"до свидания / пока",ex:"Goodbye! See you tomorrow.",lv:"A1",cat:"daily"},
{en:"please",ph:"pliːz",ru:"пожалуйста",ex:"Please pass me the salt.",lv:"A1",cat:"daily"},
{en:"thank you",ph:"ˈθæŋk juː",ru:"спасибо",ex:"Thank you for your help.",lv:"A1",cat:"daily"},
{en:"sorry",ph:"ˈsɒri",ru:"извините / простите",ex:"Sorry, I didn't mean to bump into you.",lv:"A1",cat:"daily"},
{en:"yes",ph:"jɛs",ru:"да",ex:"Yes, I would like some coffee.",lv:"A1",cat:"daily"},
{en:"no",ph:"nəʊ",ru:"нет",ex:"No, thank you, I'm not hungry.",lv:"A1",cat:"daily"},
{en:"good morning",ph:"ɡʊd ˈmɔːnɪŋ",ru:"доброе утро",ex:"Good morning! Did you sleep well?",lv:"A1",cat:"daily"},
{en:"good night",ph:"ɡʊd naɪt",ru:"спокойной ночи",ex:"Good night, sweet dreams.",lv:"A1",cat:"daily"},
{en:"name",ph:"neɪm",ru:"имя / название",ex:"My name is Anna.",lv:"A1",cat:"daily"},
{en:"today",ph:"təˈdeɪ",ru:"сегодня",ex:"Today is a sunny day.",lv:"A1",cat:"daily"},
{en:"tomorrow",ph:"təˈmɒrəʊ",ru:"завтра",ex:"I will call you tomorrow.",lv:"A1",cat:"daily"},
{en:"yesterday",ph:"ˈjɛstədeɪ",ru:"вчера",ex:"I met her yesterday at the market.",lv:"A1",cat:"daily"},
{en:"now",ph:"naʊ",ru:"сейчас / теперь",ex:"I am busy now, please wait.",lv:"A1",cat:"daily"},
{en:"here",ph:"hɪə",ru:"здесь / вот",ex:"Come here, I need to show you something.",lv:"A1",cat:"daily"},
{en:"there",ph:"ðɛə",ru:"там / туда",ex:"The keys are over there on the table.",lv:"A1",cat:"daily"},
{en:"where",ph:"wɛə",ru:"где / куда",ex:"Where is the nearest bus stop?",lv:"A1",cat:"daily"},
{en:"what",ph:"wɒt",ru:"что / какой",ex:"What is your phone number?",lv:"A1",cat:"daily"},
{en:"who",ph:"huː",ru:"кто",ex:"Who is that woman?",lv:"A1",cat:"daily"},
{en:"how",ph:"haʊ",ru:"как",ex:"How do I get to the city centre?",lv:"A1",cat:"daily"},
{en:"mother",ph:"ˈmʌðə",ru:"мама / мать",ex:"My mother makes delicious soup.",lv:"A1",cat:"family"},
{en:"father",ph:"ˈfɑːðə",ru:"папа / отец",ex:"My father works as an engineer.",lv:"A1",cat:"family"},
{en:"sister",ph:"ˈsɪstə",ru:"сестра",ex:"I have one sister and two brothers.",lv:"A1",cat:"family"},
{en:"brother",ph:"ˈbrʌðə",ru:"брат",ex:"My brother is five years older than me.",lv:"A1",cat:"family"},
{en:"son",ph:"sʌn",ru:"сын",ex:"Their son just started school.",lv:"A1",cat:"family"},
{en:"daughter",ph:"ˈdɔːtə",ru:"дочь",ex:"She has a daughter named Lily.",lv:"A1",cat:"family"},
{en:"husband",ph:"ˈhʌzbənd",ru:"муж",ex:"Her husband is a doctor.",lv:"A1",cat:"family"},
{en:"wife",ph:"waɪf",ru:"жена",ex:"His wife works at the library.",lv:"A1",cat:"family"},
{en:"baby",ph:"ˈbeɪbi",ru:"малыш / ребёнок",ex:"The baby is sleeping in the cot.",lv:"A1",cat:"family"},
{en:"family",ph:"ˈfæmɪli",ru:"семья",ex:"We have a big family reunion every year.",lv:"A1",cat:"family"},
{en:"cat",ph:"kæt",ru:"кошка / кот",ex:"Our cat sleeps on the sofa all day.",lv:"A1",cat:"animals"},
{en:"dog",ph:"dɒɡ",ru:"собака",ex:"The dog barks at every stranger.",lv:"A1",cat:"animals"},
{en:"bird",ph:"bɜːd",ru:"птица",ex:"A bird is singing outside my window.",lv:"A1",cat:"animals"},
{en:"fish",ph:"fɪʃ",ru:"рыба",ex:"We have three fish in a bowl.",lv:"A1",cat:"animals"},
{en:"horse",ph:"hɔːs",ru:"лошадь",ex:"She rides a horse every weekend.",lv:"A1",cat:"animals"},
{en:"cow",ph:"kaʊ",ru:"корова",ex:"The cow is grazing in the field.",lv:"A1",cat:"animals"},
{en:"pig",ph:"pɪɡ",ru:"свинья",ex:"The pig rolled in the mud.",lv:"A1",cat:"animals"},
{en:"rabbit",ph:"ˈræbɪt",ru:"кролик",ex:"My daughter has a white rabbit.",lv:"A1",cat:"animals"},
{en:"duck",ph:"dʌk",ru:"утка",ex:"A duck swam across the pond.",lv:"A1",cat:"animals"},
{en:"mouse",ph:"maʊs",ru:"мышь",ex:"The mouse ran under the sofa.",lv:"A1",cat:"animals"},
{en:"red",ph:"rɛd",ru:"красный",ex:"She wore a red dress to the party.",lv:"A1",cat:"colors"},
{en:"blue",ph:"bluː",ru:"синий / голубой",ex:"The sky is bright blue today.",lv:"A1",cat:"colors"},
{en:"green",ph:"ɡriːn",ru:"зелёный",ex:"The grass is green after the rain.",lv:"A1",cat:"colors"},
{en:"yellow",ph:"ˈjɛləʊ",ru:"жёлтый",ex:"She painted the wall yellow.",lv:"A1",cat:"colors"},
{en:"white",ph:"waɪt",ru:"белый",ex:"He bought a white shirt for the interview.",lv:"A1",cat:"colors"},
{en:"black",ph:"blæk",ru:"чёрный",ex:"The cat has black and white fur.",lv:"A1",cat:"colors"},
{en:"orange",ph:"ˈɒrɪndʒ",ru:"оранжевый",ex:"He painted the door orange.",lv:"A1",cat:"colors"},
{en:"pink",ph:"pɪŋk",ru:"розовый",ex:"She likes wearing pink scarves.",lv:"A1",cat:"colors"},
{en:"brown",ph:"braʊn",ru:"коричневый",ex:"The bear has dark brown fur.",lv:"A1",cat:"colors"},
{en:"grey",ph:"ɡreɪ",ru:"серый",ex:"His coat is grey with black buttons.",lv:"A1",cat:"colors"},
{en:"one",ph:"wʌn",ru:"один",ex:"I need just one more minute.",lv:"A1",cat:"numbers"},
{en:"two",ph:"tuː",ru:"два",ex:"She has two cats at home.",lv:"A1",cat:"numbers"},
{en:"three",ph:"θriː",ru:"три",ex:"I'll be back in three days.",lv:"A1",cat:"numbers"},
{en:"four",ph:"fɔː",ru:"четыре",ex:"The table has four legs.",lv:"A1",cat:"numbers"},
{en:"five",ph:"faɪv",ru:"пять",ex:"Please call me at five o'clock.",lv:"A1",cat:"numbers"},
{en:"ten",ph:"tɛn",ru:"десять",ex:"The shop closes at ten.",lv:"A1",cat:"numbers"},
{en:"hundred",ph:"ˈhʌndrəd",ru:"сто",ex:"There were a hundred people at the concert.",lv:"A1",cat:"numbers"},
{en:"first",ph:"fɜːst",ru:"первый",ex:"She was the first to arrive.",lv:"A1",cat:"numbers"},
{en:"second",ph:"ˈsɛkənd",ru:"второй / секунда",ex:"He finished in second place.",lv:"A1",cat:"numbers"},
{en:"last",ph:"lɑːst",ru:"последний",ex:"This is the last bus of the evening.",lv:"A1",cat:"numbers"},
{en:"bread",ph:"brɛd",ru:"хлеб",ex:"I buy fresh bread every morning.",lv:"A1",cat:"food"},
{en:"water",ph:"ˈwɔːtə",ru:"вода",ex:"Can I have a glass of water, please?",lv:"A1",cat:"food"},
{en:"milk",ph:"mɪlk",ru:"молоко",ex:"I put milk in my tea.",lv:"A1",cat:"food"},
{en:"egg",ph:"ɛɡ",ru:"яйцо",ex:"I eat two eggs for breakfast.",lv:"A1",cat:"food"},
{en:"apple",ph:"ˈæpəl",ru:"яблоко",ex:"She packed an apple in her lunch bag.",lv:"A1",cat:"food"},
{en:"banana",ph:"bəˈnɑːnə",ru:"банан",ex:"He eats a banana every morning.",lv:"A1",cat:"food"},
{en:"rice",ph:"raɪs",ru:"рис",ex:"We had rice and vegetables for dinner.",lv:"A1",cat:"food"},
{en:"soup",ph:"suːp",ru:"суп",ex:"She made a large pot of tomato soup.",lv:"A1",cat:"food"},
{en:"coffee",ph:"ˈkɒfi",ru:"кофе",ex:"Would you like a cup of coffee?",lv:"A1",cat:"food"},
{en:"tea",ph:"tiː",ru:"чай",ex:"I drink green tea every evening.",lv:"A1",cat:"food"},
{en:"shirt",ph:"ʃɜːt",ru:"рубашка",ex:"He always wears a white shirt to work.",lv:"A1",cat:"clothing"},
{en:"trousers",ph:"ˈtraʊzəz",ru:"брюки",ex:"These trousers are too long for me.",lv:"A1",cat:"clothing"},
{en:"dress",ph:"drɛs",ru:"платье",ex:"She bought a beautiful dress for the wedding.",lv:"A1",cat:"clothing"},
{en:"shoes",ph:"ʃuːz",ru:"туфли / обувь",ex:"My shoes are wet from the rain.",lv:"A1",cat:"clothing"},
{en:"hat",ph:"hæt",ru:"шляпа / шапка",ex:"He wears a hat when it is cold.",lv:"A1",cat:"clothing"},
{en:"coat",ph:"kəʊt",ru:"пальто",ex:"Put on your coat, it is cold outside.",lv:"A1",cat:"clothing"},
{en:"jacket",ph:"ˈdʒækɪt",ru:"куртка / пиджак",ex:"He forgot his jacket on the bus.",lv:"A1",cat:"clothing"},
{en:"socks",ph:"sɒks",ru:"носки",ex:"I need to buy new socks.",lv:"A1",cat:"clothing"},
{en:"scarf",ph:"skɑːf",ru:"шарф",ex:"She wrapped the scarf around her neck.",lv:"A1",cat:"clothing"},
{en:"gloves",ph:"ɡlʌvz",ru:"перчатки",ex:"I left my gloves at the office.",lv:"A1",cat:"clothing"},
{en:"sun",ph:"sʌn",ru:"солнце",ex:"The sun rises in the east.",lv:"A1",cat:"weather"},
{en:"rain",ph:"reɪn",ru:"дождь",ex:"It started to rain on the way home.",lv:"A1",cat:"weather"},
{en:"snow",ph:"snəʊ",ru:"снег",ex:"The children played in the snow.",lv:"A1",cat:"weather"},
{en:"wind",ph:"wɪnd",ru:"ветер",ex:"A strong wind blew the leaves off the trees.",lv:"A1",cat:"weather"},
{en:"cloud",ph:"klaʊd",ru:"облако / туча",ex:"A big cloud covered the sun.",lv:"A1",cat:"weather"},
{en:"hot",ph:"hɒt",ru:"жаркий / горячий",ex:"It is very hot today, drink more water.",lv:"A1",cat:"weather"},
{en:"cold",ph:"kəʊld",ru:"холодный / холод",ex:"The weather is cold in December.",lv:"A1",cat:"weather"},
{en:"warm",ph:"wɔːm",ru:"тёплый",ex:"It is warm enough to go outside without a coat.",lv:"A1",cat:"weather"},
{en:"fog",ph:"fɒɡ",ru:"туман",ex:"The fog made it hard to drive this morning.",lv:"A1",cat:"weather"},
{en:"ice",ph:"aɪs",ru:"лёд",ex:"Be careful, there is ice on the road.",lv:"A1",cat:"weather"},
{en:"car",ph:"kɑː",ru:"машина / автомобиль",ex:"She drives to work every day by car.",lv:"A1",cat:"transport"},
{en:"bus",ph:"bʌs",ru:"автобус",ex:"The bus arrives at half past eight.",lv:"A1",cat:"transport"},
{en:"train",ph:"treɪn",ru:"поезд",ex:"We took the train to the capital.",lv:"A1",cat:"transport"},
{en:"plane",ph:"pleɪn",ru:"самолёт",ex:"The plane takes off in two hours.",lv:"A1",cat:"transport"},
{en:"bike",ph:"baɪk",ru:"велосипед",ex:"He rides his bike to school every day.",lv:"A1",cat:"transport"},
{en:"taxi",ph:"ˈtæksi",ru:"такси",ex:"We took a taxi from the airport.",lv:"A1",cat:"transport"},
{en:"road",ph:"rəʊd",ru:"дорога",ex:"The road is closed due to construction.",lv:"A1",cat:"transport"},
{en:"ticket",ph:"ˈtɪkɪt",ru:"билет",ex:"I bought a return ticket to London.",lv:"A1",cat:"transport"},
{en:"station",ph:"ˈsteɪʃən",ru:"станция / вокзал",ex:"Meet me at the station at noon.",lv:"A1",cat:"transport"},
{en:"stop",ph:"stɒp",ru:"остановка / стоп",ex:"We get off at the next stop.",lv:"A1",cat:"transport"},
{en:"house",ph:"haʊs",ru:"дом",ex:"They live in a small house near the park.",lv:"A1",cat:"home"},
{en:"room",ph:"ruːm",ru:"комната",ex:"My room is on the second floor.",lv:"A1",cat:"home"},
{en:"door",ph:"dɔː",ru:"дверь",ex:"Please close the door when you leave.",lv:"A1",cat:"home"},
{en:"window",ph:"ˈwɪndəʊ",ru:"окно",ex:"Open the window, it is stuffy in here.",lv:"A1",cat:"home"},
{en:"table",ph:"ˈteɪbəl",ru:"стол",ex:"The dishes are on the kitchen table.",lv:"A1",cat:"home"},
{en:"chair",ph:"tʃɛə",ru:"стул",ex:"Please have a seat on the chair.",lv:"A1",cat:"home"},
{en:"bed",ph:"bɛd",ru:"кровать",ex:"She made the bed before leaving.",lv:"A1",cat:"home"},
{en:"kitchen",ph:"ˈkɪtʃɪn",ru:"кухня",ex:"The kitchen smells of fresh bread.",lv:"A1",cat:"home"},
{en:"bathroom",ph:"ˈbɑːθruːm",ru:"ванная комната",ex:"The bathroom is at the end of the corridor.",lv:"A1",cat:"home"},
{en:"key",ph:"kiː",ru:"ключ",ex:"I forgot my key inside the flat.",lv:"A1",cat:"home"},
{en:"head",ph:"hɛd",ru:"голова",ex:"She shook her head to say no.",lv:"A1",cat:"body"},
{en:"eye",ph:"aɪ",ru:"глаз",ex:"He has bright blue eyes.",lv:"A1",cat:"body"},
{en:"ear",ph:"ɪə",ru:"ухо",ex:"The doctor looked inside my ear.",lv:"A1",cat:"body"},
{en:"mouth",ph:"maʊθ",ru:"рот",ex:"Open your mouth and say 'Ah'.",lv:"A1",cat:"body"},
{en:"nose",ph:"nəʊz",ru:"нос",ex:"He blew his nose into a handkerchief.",lv:"A1",cat:"body"},
{en:"hand",ph:"hænd",ru:"рука (кисть)",ex:"She washed her hands before eating.",lv:"A1",cat:"body"},
{en:"arm",ph:"ɑːm",ru:"рука (рука целиком)",ex:"He broke his arm playing football.",lv:"A1",cat:"body"},
{en:"leg",ph:"lɛɡ",ru:"нога",ex:"She hurt her leg during the run.",lv:"A1",cat:"body"},
{en:"foot",ph:"fʊt",ru:"стопа / нога (ступня)",ex:"I have a blister on my left foot.",lv:"A1",cat:"body"},
{en:"back",ph:"bæk",ru:"спина",ex:"My back hurts after sitting all day.",lv:"A1",cat:"body"},
{en:"shop",ph:"ʃɒp",ru:"магазин",ex:"There is a small shop around the corner.",lv:"A1",cat:"shopping"},
{en:"price",ph:"praɪs",ru:"цена",ex:"What is the price of this jacket?",lv:"A1",cat:"shopping"},
{en:"money",ph:"ˈmʌni",ru:"деньги",ex:"I don't have enough money with me.",lv:"A1",cat:"shopping"},
{en:"buy",ph:"baɪ",ru:"покупать / купить",ex:"I want to buy a new phone.",lv:"A1",cat:"shopping"},
{en:"sell",ph:"sɛl",ru:"продавать / продать",ex:"They sell fresh fruit at the market.",lv:"A1",cat:"shopping"},
{en:"cheap",ph:"tʃiːp",ru:"дешёвый",ex:"This restaurant is cheap but very good.",lv:"A1",cat:"shopping"},
{en:"expensive",ph:"ɪkˈspɛnsɪv",ru:"дорогой",ex:"That watch is too expensive for me.",lv:"A1",cat:"shopping"},
{en:"bag",ph:"bæɡ",ru:"сумка / пакет",ex:"She carried a big bag of groceries.",lv:"A1",cat:"shopping"},
{en:"pay",ph:"peɪ",ru:"платить / заплатить",ex:"Can I pay by card?",lv:"A1",cat:"shopping"},
{en:"market",ph:"ˈmɑːkɪt",ru:"рынок",ex:"We buy vegetables at the local market.",lv:"A1",cat:"shopping"},
{en:"job",ph:"dʒɒb",ru:"работа / должность",ex:"She found a new job in the city.",lv:"A1",cat:"work"},
{en:"work",ph:"wɜːk",ru:"работа / работать",ex:"I work five days a week.",lv:"A1",cat:"work"},
{en:"office",ph:"ˈɒfɪs",ru:"офис",ex:"He works in a modern office downtown.",lv:"A1",cat:"work"},
{en:"boss",ph:"bɒs",ru:"начальник / шеф",ex:"My boss gave me a day off.",lv:"A1",cat:"work"},
{en:"meeting",ph:"ˈmiːtɪŋ",ru:"встреча / собрание",ex:"We have a team meeting every Monday.",lv:"A1",cat:"work"},
{en:"write",ph:"raɪt",ru:"писать",ex:"Please write your name on the form.",lv:"A1",cat:"work"},
{en:"read",ph:"riːd",ru:"читать",ex:"I read the report this morning.",lv:"A1",cat:"work"},
{en:"speak",ph:"spiːk",ru:"говорить",ex:"She speaks three languages fluently.",lv:"A1",cat:"work"},
{en:"help",ph:"hɛlp",ru:"помощь / помогать",ex:"Can you help me with this task?",lv:"A1",cat:"work"},
{en:"question",ph:"ˈkwɛstʃən",ru:"вопрос",ex:"Do you have any questions?",lv:"A1",cat:"work"},
{en:"doctor",ph:"ˈdɒktə",ru:"врач / доктор",ex:"The doctor will see you at three o'clock.",lv:"A1",cat:"medical"},
{en:"hospital",ph:"ˈhɒspɪtəl",ru:"больница",ex:"He was taken to hospital by ambulance.",lv:"A1",cat:"medical"},
{en:"medicine",ph:"ˈmɛdsɪn",ru:"лекарство / медицина",ex:"Take this medicine twice a day.",lv:"A1",cat:"medical"},
{en:"pain",ph:"peɪn",ru:"боль",ex:"I have a sharp pain in my shoulder.",lv:"A1",cat:"medical"},
{en:"ill",ph:"ɪl",ru:"больной / нездоровый",ex:"She stayed home because she felt ill.",lv:"A1",cat:"medical"},
{en:"phone",ph:"fəʊn",ru:"телефон",ex:"My phone needs charging.",lv:"A1",cat:"technology"},
{en:"computer",ph:"kəmˈpjuːtə",ru:"компьютер",ex:"I use the computer for work every day.",lv:"A1",cat:"technology"},
{en:"internet",ph:"ˈɪntənɛt",ru:"интернет",ex:"The internet connection is slow today.",lv:"A1",cat:"technology"},
{en:"email",ph:"ˈiːmeɪl",ru:"электронная почта / имейл",ex:"Send me an email with the details.",lv:"A1",cat:"technology"},
{en:"camera",ph:"ˈkæmərə",ru:"фотоаппарат / камера",ex:"She took photos with her new camera.",lv:"A1",cat:"technology"},
{en:"music",ph:"ˈmjuːzɪk",ru:"музыка",ex:"I listen to music while I exercise.",lv:"A1",cat:"entertainment"},
{en:"film",ph:"fɪlm",ru:"фильм",ex:"Let's watch a film tonight.",lv:"A1",cat:"entertainment"},
{en:"book",ph:"bʊk",ru:"книга",ex:"She reads at least one book a month.",lv:"A1",cat:"entertainment"},
{en:"game",ph:"ɡeɪm",ru:"игра",ex:"The children played a board game.",lv:"A1",cat:"entertainment"},
{en:"sport",ph:"spɔːt",ru:"спорт",ex:"Football is the most popular sport here.",lv:"A1",cat:"entertainment"},
{en:"bank",ph:"bæŋk",ru:"банк",ex:"I need to go to the bank to withdraw cash.",lv:"A1",cat:"bank"},
{en:"card",ph:"kɑːd",ru:"карточка / карта",ex:"Do you accept credit card payment?",lv:"A1",cat:"bank"},
{en:"cash",ph:"kæʃ",ru:"наличные",ex:"I only have cash, no card.",lv:"A1",cat:"bank"},
{en:"account",ph:"əˈkaʊnt",ru:"счёт / аккаунт",ex:"I opened a bank account last week.",lv:"A1",cat:"bank"},
{en:"coin",ph:"kɔɪn",ru:"монета",ex:"He found an old coin in the garden.",lv:"A1",cat:"bank"},
{en:"address",ph:"ˈædrɛs",ru:"адрес",ex:"Please write your home address on the form.",lv:"A1",cat:"daily"},
{en:"number",ph:"ˈnʌmbə",ru:"номер / число",ex:"What is your flat number?",lv:"A1",cat:"daily"},
{en:"city",ph:"ˈsɪti",ru:"город",ex:"She moved to the city for university.",lv:"A1",cat:"daily"},
{en:"street",ph:"striːt",ru:"улица",ex:"The hotel is on the main street.",lv:"A1",cat:"daily"},
{en:"school",ph:"skuːl",ru:"школа",ex:"The children walk to school together.",lv:"A1",cat:"daily"},
{en:"friend",ph:"frɛnd",ru:"друг / подруга",ex:"She is my best friend from childhood.",lv:"A1",cat:"family"},
{en:"boy",ph:"bɔɪ",ru:"мальчик",ex:"A little boy was playing in the park.",lv:"A1",cat:"family"},
{en:"girl",ph:"ɡɜːl",ru:"девочка / девушка",ex:"The girl in the red coat is my niece.",lv:"A1",cat:"family"},
{en:"man",ph:"mæn",ru:"мужчина / человек",ex:"A tall man opened the door.",lv:"A1",cat:"family"},
{en:"woman",ph:"ˈwʊmən",ru:"женщина",ex:"The woman at the desk will help you.",lv:"A1",cat:"family"},
{en:"child",ph:"tʃaɪld",ru:"ребёнок",ex:"Every child needs love and care.",lv:"A1",cat:"family"},
{en:"people",ph:"ˈpiːpəl",ru:"люди",ex:"Many people came to the festival.",lv:"A1",cat:"daily"},
{en:"time",ph:"taɪm",ru:"время",ex:"What time does the train leave?",lv:"A1",cat:"daily"},
{en:"day",ph:"deɪ",ru:"день",ex:"Have a nice day!",lv:"A1",cat:"daily"},
{en:"night",ph:"naɪt",ru:"ночь",ex:"The stars are bright tonight.",lv:"A1",cat:"daily"},
{en:"week",ph:"wiːk",ru:"неделя",ex:"I go swimming twice a week.",lv:"A1",cat:"daily"},
{en:"year",ph:"jɪə",ru:"год",ex:"She has lived here for ten years.",lv:"A1",cat:"daily"},
{en:"morning",ph:"ˈmɔːnɪŋ",ru:"утро",ex:"I go jogging every morning.",lv:"A1",cat:"daily"},
{en:"evening",ph:"ˈiːvnɪŋ",ru:"вечер",ex:"We usually eat dinner in the evening.",lv:"A1",cat:"daily"},
{en:"eat",ph:"iːt",ru:"есть / кушать",ex:"What do you usually eat for lunch?",lv:"A1",cat:"food"},
{en:"drink",ph:"drɪŋk",ru:"пить / напиток",ex:"I like to drink warm tea in the evening.",lv:"A1",cat:"food"},
{en:"lunch",ph:"lʌntʃ",ru:"обед",ex:"We had lunch at the new café.",lv:"A1",cat:"food"},
{en:"dinner",ph:"ˈdɪnə",ru:"ужин",ex:"Dinner is ready, come to the table.",lv:"A1",cat:"food"},
{en:"breakfast",ph:"ˈbrɛkfəst",ru:"завтрак",ex:"I always eat breakfast before work.",lv:"A1",cat:"food"},
{en:"sugar",ph:"ˈʃʊɡə",ru:"сахар",ex:"Do you take sugar in your coffee?",lv:"A1",cat:"food"},
{en:"salt",ph:"sɒlt",ru:"соль",ex:"Pass me the salt, please.",lv:"A1",cat:"food"},
{en:"meat",ph:"miːt",ru:"мясо",ex:"I don't eat meat on Mondays.",lv:"A1",cat:"food"},
{en:"cheese",ph:"tʃiːz",ru:"сыр",ex:"She put cheese on the sandwich.",lv:"A1",cat:"food"},
{en:"orange",ph:"ˈɒrɪndʒ",ru:"апельсин",ex:"He squeezed an orange for fresh juice.",lv:"A1",cat:"food"},
{en:"floor",ph:"flɔː",ru:"пол / этаж",ex:"The cat is sleeping on the floor.",lv:"A1",cat:"home"},
{en:"wall",ph:"wɔːl",ru:"стена",ex:"They painted the walls white.",lv:"A1",cat:"home"},
{en:"garden",ph:"ˈɡɑːdən",ru:"сад / огород",ex:"She grows tomatoes in her garden.",lv:"A1",cat:"home"},
{en:"sofa",ph:"ˈsəʊfə",ru:"диван",ex:"He fell asleep on the sofa.",lv:"A1",cat:"home"},
{en:"lamp",ph:"læmp",ru:"лампа",ex:"Turn on the lamp, it is getting dark.",lv:"A1",cat:"home"},
{en:"nurse",ph:"nɜːs",ru:"медсестра / медбрат",ex:"The nurse checked my blood pressure.",lv:"A1",cat:"medical"},
{en:"tooth",ph:"tuːθ",ru:"зуб",ex:"My tooth hurts, I need to see a dentist.",lv:"A1",cat:"body"},
{en:"hair",ph:"hɛə",ru:"волосы",ex:"She has long dark hair.",lv:"A1",cat:"body"},
{en:"heart",ph:"hɑːt",ru:"сердце",ex:"Exercise is good for your heart.",lv:"A1",cat:"body"},
{en:"stomach",ph:"ˈstʌmək",ru:"желудок / живот",ex:"My stomach hurts after eating.",lv:"A1",cat:"body"},
{en:"grandfather",ph:"ˈɡrænfɑːðə",ru:"дедушка",ex:"My grandfather tells great stories.",lv:"A1",cat:"family"},
{en:"grandmother",ph:"ˈɡrænmʌðə",ru:"бабушка",ex:"My grandmother bakes the best cakes.",lv:"A1",cat:"family"},
{en:"uncle",ph:"ˈʌŋkəl",ru:"дядя",ex:"My uncle lives in another city.",lv:"A1",cat:"family"},
{en:"aunt",ph:"ɑːnt",ru:"тётя",ex:"Her aunt gave her a beautiful ring.",lv:"A1",cat:"family"},
{en:"ship",ph:"ʃɪp",ru:"корабль",ex:"The ship arrived at the port.",lv:"A1",cat:"transport"},
{en:"walk",ph:"wɔːk",ru:"идти пешком / прогулка",ex:"Let's walk to the park.",lv:"A1",cat:"transport"},
{en:"run",ph:"rʌn",ru:"бежать / бег",ex:"I run three kilometres every morning.",lv:"A1",cat:"transport"},
{en:"drive",ph:"draɪv",ru:"водить / ехать",ex:"He drives to the office every day.",lv:"A1",cat:"transport"},
{en:"open",ph:"ˈəʊpən",ru:"открытый / открывать",ex:"The shop opens at nine.",lv:"A1",cat:"daily"},
{en:"close",ph:"kləʊz",ru:"закрывать / закрытый",ex:"Please close the window.",lv:"A1",cat:"daily"},
{en:"big",ph:"bɪɡ",ru:"большой",ex:"They live in a big house.",lv:"A1",cat:"daily"},
{en:"small",ph:"smɔːl",ru:"маленький",ex:"I need a small bag for my phone.",lv:"A1",cat:"daily"},
{en:"new",ph:"njuː",ru:"новый",ex:"She bought a new dress for the party.",lv:"A1",cat:"daily"},
{en:"old",ph:"əʊld",ru:"старый / пожилой",ex:"This is an old photo of my parents.",lv:"A1",cat:"daily"},
{en:"good",ph:"ɡʊd",ru:"хороший / хорошо",ex:"That is a very good idea.",lv:"A1",cat:"daily"},
{en:"bad",ph:"bæd",ru:"плохой / плохо",ex:"The weather was bad all week.",lv:"A1",cat:"daily"},
{en:"happy",ph:"ˈhæpi",ru:"счастливый / радостный",ex:"She looks very happy today.",lv:"A1",cat:"daily"},
{en:"tired",ph:"ˈtaɪəd",ru:"уставший",ex:"I am so tired after the long journey.",lv:"A1",cat:"daily"},
{en:"apartment",ph:"əˈpɑːtmənt",ru:"квартира",ex:"They rent a small apartment in the centre.",lv:"A2",cat:"home"},
{en:"neighbour",ph:"ˈneɪbə",ru:"сосед / соседка",ex:"My neighbour helped me carry the boxes.",lv:"A2",cat:"home"},
{en:"furniture",ph:"ˈfɜːnɪtʃə",ru:"мебель",ex:"They bought new furniture for the living room.",lv:"A2",cat:"home"},
{en:"shelf",ph:"ʃɛlf",ru:"полка",ex:"The books are on the top shelf.",lv:"A2",cat:"home"},
{en:"curtain",ph:"ˈkɜːtən",ru:"шторы / занавеска",ex:"She opened the curtains to let in the light.",lv:"A2",cat:"home"},
{en:"stairs",ph:"stɛəz",ru:"лестница",ex:"Take the stairs to the third floor.",lv:"A2",cat:"home"},
{en:"ceiling",ph:"ˈsiːlɪŋ",ru:"потолок",ex:"The ceiling in the old house is very high.",lv:"A2",cat:"home"},
{en:"cupboard",ph:"ˈkʌbəd",ru:"шкаф / шкафчик",ex:"The cups are in the cupboard above the sink.",lv:"A2",cat:"home"},
{en:"sink",ph:"sɪŋk",ru:"раковина",ex:"He washed the dishes in the sink.",lv:"A2",cat:"home"},
{en:"mirror",ph:"ˈmɪrə",ru:"зеркало",ex:"She checked her look in the mirror before leaving.",lv:"A2",cat:"home"},
{en:"oven",ph:"ˈʌvən",ru:"духовка / плита",ex:"Preheat the oven to 180 degrees.",lv:"A2",cat:"home"},
{en:"fridge",ph:"frɪdʒ",ru:"холодильник",ex:"Put the leftovers in the fridge.",lv:"A2",cat:"home"},
{en:"washing machine",ph:"ˈwɒʃɪŋ məˈʃiːn",ru:"стиральная машина",ex:"The washing machine is broken again.",lv:"A2",cat:"home"},
{en:"balcony",ph:"ˈbælkəni",ru:"балкон",ex:"I drink my morning coffee on the balcony.",lv:"A2",cat:"home"},
{en:"garage",ph:"ˈɡærɑːʒ",ru:"гараж",ex:"He keeps his tools in the garage.",lv:"A2",cat:"home"},
{en:"chicken",ph:"ˈtʃɪkɪn",ru:"курица",ex:"She roasted a chicken for Sunday dinner.",lv:"A2",cat:"food"},
{en:"fish",ph:"fɪʃ",ru:"рыба",ex:"We had grilled fish and salad for lunch.",lv:"A2",cat:"food"},
{en:"vegetable",ph:"ˈvɛdʒtəbəl",ru:"овощ",ex:"Try to eat more vegetables every day.",lv:"A2",cat:"food"},
{en:"potato",ph:"pəˈteɪtəʊ",ru:"картофель / картошка",ex:"She peeled and boiled three potatoes.",lv:"A2",cat:"food"},
{en:"tomato",ph:"təˈmɑːtəʊ",ru:"помидор",ex:"I sliced a tomato for the salad.",lv:"A2",cat:"food"},
{en:"onion",ph:"ˈʌnjən",ru:"лук",ex:"Fry the onion until it is golden.",lv:"A2",cat:"food"},
{en:"carrot",ph:"ˈkærət",ru:"морковь",ex:"Carrots are good for your eyesight.",lv:"A2",cat:"food"},
{en:"salad",ph:"ˈsæləd",ru:"салат",ex:"I ordered a green salad with my meal.",lv:"A2",cat:"food"},
{en:"pasta",ph:"ˈpæstə",ru:"паста / макароны",ex:"She cooked pasta with tomato sauce.",lv:"A2",cat:"food"},
{en:"butter",ph:"ˈbʌtə",ru:"масло (сливочное)",ex:"Spread butter on the bread.",lv:"A2",cat:"food"},
{en:"oil",ph:"ɔɪl",ru:"масло (растительное) / нефть",ex:"Heat the oil in the pan before adding the garlic.",lv:"A2",cat:"food"},
{en:"flour",ph:"flaʊə",ru:"мука",ex:"Mix the flour and sugar together.",lv:"A2",cat:"food"},
{en:"cake",ph:"keɪk",ru:"торт / пирог",ex:"She baked a birthday cake for her son.",lv:"A2",cat:"food"},
{en:"sandwich",ph:"ˈsænwɪdʒ",ru:"бутерброд / сэндвич",ex:"I made a cheese and tomato sandwich.",lv:"A2",cat:"food"},
{en:"juice",ph:"dʒuːs",ru:"сок",ex:"Would you like a glass of orange juice?",lv:"A2",cat:"food"},
{en:"wine",ph:"waɪn",ru:"вино",ex:"They ordered a bottle of red wine.",lv:"A2",cat:"food"},
{en:"beer",ph:"bɪə",ru:"пиво",ex:"He ordered a cold beer at the bar.",lv:"A2",cat:"food"},
{en:"spicy",ph:"ˈspaɪsi",ru:"острый / пряный",ex:"This curry is very spicy.",lv:"A2",cat:"food"},
{en:"sweet",ph:"swiːt",ru:"сладкий / сладость",ex:"The dessert was too sweet for my taste.",lv:"A2",cat:"food"},
{en:"bitter",ph:"ˈbɪtə",ru:"горький",ex:"Dark chocolate has a bitter taste.",lv:"A2",cat:"food"},
{en:"subway",ph:"ˈsʌbweɪ",ru:"метро / подземный переход",ex:"I take the subway to work every morning.",lv:"A2",cat:"transport"},
{en:"tram",ph:"træm",ru:"трамвай",ex:"The tram stops right in front of my building.",lv:"A2",cat:"transport"},
{en:"ferry",ph:"ˈfɛri",ru:"паром",ex:"We crossed the river by ferry.",lv:"A2",cat:"transport"},
{en:"motorway",ph:"ˈməʊtəweɪ",ru:"автомагистраль",ex:"The motorway was closed because of an accident.",lv:"A2",cat:"transport"},
{en:"traffic",ph:"ˈtræfɪk",ru:"движение / трафик",ex:"There was heavy traffic on the way to the airport.",lv:"A2",cat:"transport"},
{en:"passenger",ph:"ˈpæsɪndʒə",ru:"пассажир",ex:"All passengers must show their tickets.",lv:"A2",cat:"transport"},
{en:"driver",ph:"ˈdraɪvə",ru:"водитель",ex:"The bus driver was very polite.",lv:"A2",cat:"transport"},
{en:"petrol",ph:"ˈpɛtrəl",ru:"бензин",ex:"I need to stop and get petrol.",lv:"A2",cat:"transport"},
{en:"parking",ph:"ˈpɑːkɪŋ",ru:"парковка",ex:"Is there free parking near the hotel?",lv:"A2",cat:"transport"},
{en:"departure",ph:"dɪˈpɑːtʃə",ru:"отправление / вылет",ex:"The departure is at half past six.",lv:"A2",cat:"transport"},
{en:"arrival",ph:"əˈraɪvəl",ru:"прибытие",ex:"The arrival time is shown on the screen.",lv:"A2",cat:"transport"},
{en:"border",ph:"ˈbɔːdə",ru:"граница",ex:"We crossed the border at midnight.",lv:"A2",cat:"transport"},
{en:"licence",ph:"ˈlaɪsəns",ru:"лицензия / водительское удостоверение",ex:"You need a licence to drive a car.",lv:"A2",cat:"transport"},
{en:"seat belt",ph:"ˈsiːt bɛlt",ru:"ремень безопасности",ex:"Always fasten your seat belt before driving.",lv:"A2",cat:"transport"},
{en:"luggage",ph:"ˈlʌɡɪdʒ",ru:"багаж",ex:"My luggage was lost at the airport.",lv:"A2",cat:"transport"},
{en:"sweater",ph:"ˈswɛtə",ru:"свитер",ex:"She wore a thick sweater in the cold weather.",lv:"A2",cat:"clothing"},
{en:"skirt",ph:"skɜːt",ru:"юбка",ex:"She bought a new skirt for the office.",lv:"A2",cat:"clothing"},
{en:"suit",ph:"suːt",ru:"костюм",ex:"He wore a dark suit to the interview.",lv:"A2",cat:"clothing"},
{en:"tie",ph:"taɪ",ru:"галстук",ex:"He always wears a tie to formal meetings.",lv:"A2",cat:"clothing"},
{en:"boots",ph:"buːts",ru:"сапоги / ботинки",ex:"She put on her boots before going out.",lv:"A2",cat:"clothing"},
{en:"uniform",ph:"ˈjuːnɪfɔːm",ru:"форма / форменная одежда",ex:"All students wear a school uniform.",lv:"A2",cat:"clothing"},
{en:"pocket",ph:"ˈpɒkɪt",ru:"карман",ex:"He kept his keys in his jacket pocket.",lv:"A2",cat:"clothing"},
{en:"button",ph:"ˈbʌtən",ru:"пуговица / кнопка",ex:"One button is missing from his coat.",lv:"A2",cat:"clothing"},
{en:"size",ph:"saɪz",ru:"размер",ex:"What size do you wear?",lv:"A2",cat:"clothing"},
{en:"cotton",ph:"ˈkɒtən",ru:"хлопок",ex:"This shirt is made of pure cotton.",lv:"A2",cat:"clothing"},
{en:"leather",ph:"ˈlɛðə",ru:"кожа",ex:"Her leather bag is very stylish.",lv:"A2",cat:"clothing"},
{en:"receipt",ph:"rɪˈsiːt",ru:"чек / квитанция",ex:"Keep your receipt in case you need to return the item.",lv:"A2",cat:"shopping"},
{en:"discount",ph:"ˈdɪskaʊnt",ru:"скидка",ex:"We get a ten percent discount with this card.",lv:"A2",cat:"shopping"},
{en:"sale",ph:"seɪl",ru:"распродажа / продажа",ex:"There is a big sale at the department store.",lv:"A2",cat:"shopping"},
{en:"queue",ph:"kjuː",ru:"очередь",ex:"There was a long queue at the checkout.",lv:"A2",cat:"shopping"},
{en:"trolley",ph:"ˈtrɒli",ru:"тележка",ex:"She filled the trolley with groceries.",lv:"A2",cat:"shopping"},
{en:"shelf",ph:"ʃɛlf",ru:"полка (магазинная)",ex:"The milk is on the top shelf.",lv:"A2",cat:"shopping"},
{en:"return",ph:"rɪˈtɜːn",ru:"вернуть / возврат",ex:"I need to return this shirt, it is the wrong size.",lv:"A2",cat:"shopping"},
{en:"exchange",ph:"ɪksˈtʃeɪndʒ",ru:"обмен / обменять",ex:"Can I exchange this for a different colour?",lv:"A2",cat:"shopping"},
{en:"supermarket",ph:"ˈsuːpəmɑːkɪt",ru:"супермаркет",ex:"I do my weekly shopping at the supermarket.",lv:"A2",cat:"shopping"},
{en:"department store",ph:"dɪˈpɑːtmənt stɔː",ru:"универмаг",ex:"She bought shoes at the department store.",lv:"A2",cat:"shopping"},
{en:"colleague",ph:"ˈkɒliːɡ",ru:"коллега",ex:"My colleague helped me finish the report.",lv:"A2",cat:"work"},
{en:"salary",ph:"ˈsæləri",ru:"зарплата",ex:"She got a pay rise last month.",lv:"A2",cat:"work"},
{en:"manager",ph:"ˈmænɪdʒə",ru:"менеджер / руководитель",ex:"The manager approved the new project.",lv:"A2",cat:"work"},
{en:"interview",ph:"ˈɪntəvjuː",ru:"интервью / собеседование",ex:"She has a job interview on Tuesday.",lv:"A2",cat:"work"},
{en:"contract",ph:"ˈkɒntrækt",ru:"контракт / договор",ex:"He signed a two-year contract.",lv:"A2",cat:"work"},
{en:"schedule",ph:"ˈʃɛdjuːl",ru:"расписание / график",ex:"Let me check my schedule for next week.",lv:"A2",cat:"work"},
{en:"deadline",ph:"ˈdɛdlaɪn",ru:"дедлайн / крайний срок",ex:"The deadline for the project is Friday.",lv:"A2",cat:"work"},
{en:"department",ph:"dɪˈpɑːtmənt",ru:"отдел",ex:"She works in the sales department.",lv:"A2",cat:"work"},
{en:"project",ph:"ˈprɒdʒɛkt",ru:"проект",ex:"They finished the project on time.",lv:"A2",cat:"work"},
{en:"experience",ph:"ɪkˈspɪəriəns",ru:"опыт",ex:"She has five years of experience in marketing.",lv:"A2",cat:"work"},
{en:"skill",ph:"skɪl",ru:"навык / умение",ex:"Good communication is a key skill.",lv:"A2",cat:"work"},
{en:"report",ph:"rɪˈpɔːt",ru:"отчёт / доклад",ex:"Please send me the report by Friday.",lv:"A2",cat:"work"},
{en:"loan",ph:"ləʊn",ru:"кредит / займ",ex:"She took out a loan to buy a car.",lv:"A2",cat:"bank"},
{en:"mortgage",ph:"ˈmɔːɡɪdʒ",ru:"ипотека",ex:"They are paying off their mortgage over twenty years.",lv:"A2",cat:"bank"},
{en:"interest",ph:"ˈɪntrəst",ru:"процент / интерес",ex:"The interest rate on this account is two percent.",lv:"A2",cat:"bank"},
{en:"transfer",ph:"ˈtrænsˌfɜː",ru:"перевод / перевести",ex:"I need to transfer money to my sister.",lv:"A2",cat:"bank"},
{en:"deposit",ph:"dɪˈpɒzɪt",ru:"вклад / депозит / взнос",ex:"She made a deposit of five hundred euros.",lv:"A2",cat:"bank"},
{en:"withdrawal",ph:"wɪðˈdrɔːəl",ru:"снятие денег / вывод",ex:"There is a fee for large withdrawals.",lv:"A2",cat:"bank"},
{en:"balance",ph:"ˈbæləns",ru:"баланс / остаток",ex:"I checked my account balance at the ATM.",lv:"A2",cat:"bank"},
{en:"currency",ph:"ˈkʌrənsi",ru:"валюта",ex:"What currency do they use in that country?",lv:"A2",cat:"bank"},
{en:"ATM",ph:"ˌeɪtiːˈɛm",ru:"банкомат",ex:"I need to find an ATM to get some cash.",lv:"A2",cat:"bank"},
{en:"invoice",ph:"ˈɪnvɔɪs",ru:"счёт-фактура / накладная",ex:"Please send the invoice by the end of the day.",lv:"A2",cat:"bank"},
{en:"symptom",ph:"ˈsɪmptəm",ru:"симптом",ex:"Coughing is one of the main symptoms of flu.",lv:"A2",cat:"medical"},
{en:"prescription",ph:"prɪˈskrɪpʃən",ru:"рецепт (медицинский)",ex:"The doctor gave me a prescription for antibiotics.",lv:"A2",cat:"medical"},
{en:"allergy",ph:"ˈælərdʒi",ru:"аллергия",ex:"She has a severe allergy to peanuts.",lv:"A2",cat:"medical"},
{en:"fever",ph:"ˈfiːvə",ru:"температура / жар",ex:"The child has a high fever and needs rest.",lv:"A2",cat:"medical"},
{en:"injection",ph:"ɪnˈdʒɛkʃən",ru:"укол / инъекция",ex:"The nurse gave him an injection.",lv:"A2",cat:"medical"},
{en:"pharmacy",ph:"ˈfɑːməsi",ru:"аптека",ex:"I bought cough syrup at the pharmacy.",lv:"A2",cat:"medical"},
{en:"blood pressure",ph:"blʌd ˈprɛʃə",ru:"кровяное давление",ex:"The doctor checked my blood pressure.",lv:"A2",cat:"medical"},
{en:"surgery",ph:"ˈsɜːdʒəri",ru:"операция / хирургия",ex:"He recovered well after the surgery.",lv:"A2",cat:"medical"},
{en:"ambulance",ph:"ˈæmbjʊləns",ru:"скорая помощь",ex:"Call an ambulance, someone has fainted.",lv:"A2",cat:"medical"},
{en:"emergency",ph:"ɪˈmɜːdʒənsi",ru:"скорая помощь / чрезвычайная ситуация",ex:"In an emergency, call 112.",lv:"A2",cat:"medical"},
{en:"appointment",ph:"əˈpɔɪntmənt",ru:"приём / запись / встреча",ex:"I have a doctor's appointment on Thursday.",lv:"A2",cat:"medical"},
{en:"temperature",ph:"ˈtɛmprɪtʃə",ru:"температура",ex:"The temperature dropped to minus five last night.",lv:"A2",cat:"weather"},
{en:"storm",ph:"stɔːm",ru:"буря / гроза",ex:"A big storm hit the coast last night.",lv:"A2",cat:"weather"},
{en:"thunder",ph:"ˈθʌndə",ru:"гром",ex:"The thunder woke everyone up at midnight.",lv:"A2",cat:"weather"},
{en:"lightning",ph:"ˈlaɪtnɪŋ",ru:"молния",ex:"We saw lightning over the mountains.",lv:"A2",cat:"weather"},
{en:"flood",ph:"flʌd",ru:"наводнение / паводок",ex:"The heavy rain caused a flood in the valley.",lv:"A2",cat:"weather"},
{en:"humidity",ph:"hjuːˈmɪdɪti",ru:"влажность",ex:"The humidity is very high in summer.",lv:"A2",cat:"weather"},
{en:"forecast",ph:"ˈfɔːkɑːst",ru:"прогноз",ex:"The weather forecast says it will rain tomorrow.",lv:"A2",cat:"weather"},
{en:"season",ph:"ˈsiːzən",ru:"сезон / время года",ex:"Autumn is my favourite season.",lv:"A2",cat:"weather"},
{en:"rainbow",ph:"ˈreɪnbəʊ",ru:"радуга",ex:"A beautiful rainbow appeared after the storm.",lv:"A2",cat:"weather"},
{en:"hail",ph:"heɪl",ru:"град",ex:"Hail damaged the crops last spring.",lv:"A2",cat:"weather"},
{en:"drizzle",ph:"ˈdrɪzəl",ru:"моросящий дождь",ex:"There was a light drizzle all morning.",lv:"A2",cat:"weather"},
{en:"sparrow",ph:"ˈspærəʊ",ru:"воробей",ex:"A sparrow sat on the window ledge.",lv:"A2",cat:"animals"},
{en:"eagle",ph:"ˈiːɡəl",ru:"орёл",ex:"The eagle soared high above the mountains.",lv:"A2",cat:"animals"},
{en:"bear",ph:"bɛə",ru:"медведь",ex:"They saw a bear in the forest.",lv:"A2",cat:"animals"},
{en:"wolf",ph:"wʊlf",ru:"волк",ex:"The wolf howled at the moon.",lv:"A2",cat:"animals"},
{en:"fox",ph:"fɒks",ru:"лиса",ex:"A fox ran across the road last night.",lv:"A2",cat:"animals"},
{en:"deer",ph:"dɪə",ru:"олень",ex:"A deer stood still at the edge of the woods.",lv:"A2",cat:"animals"},
{en:"snake",ph:"sneɪk",ru:"змея",ex:"She was frightened by a snake in the garden.",lv:"A2",cat:"animals"},
{en:"frog",ph:"frɒɡ",ru:"лягушка",ex:"We heard frogs croaking near the pond.",lv:"A2",cat:"animals"},
{en:"butterfly",ph:"ˈbʌtəflaɪ",ru:"бабочка",ex:"A beautiful butterfly landed on the flower.",lv:"A2",cat:"animals"},
{en:"bee",ph:"biː",ru:"пчела",ex:"A bee stung me on the arm.",lv:"A2",cat:"animals"},
{en:"spider",ph:"ˈspaɪdə",ru:"паук",ex:"There is a big spider in the corner.",lv:"A2",cat:"animals"},
{en:"parrot",ph:"ˈpærət",ru:"попугай",ex:"The parrot repeated everything I said.",lv:"A2",cat:"animals"},
{en:"sheep",ph:"ʃiːp",ru:"овца",ex:"A flock of sheep crossed the road.",lv:"A2",cat:"animals"},
{en:"goat",ph:"ɡəʊt",ru:"коза",ex:"The goat escaped from the field.",lv:"A2",cat:"animals"},
{en:"hen",ph:"hɛn",ru:"курица (самка)",ex:"The hen laid an egg this morning.",lv:"A2",cat:"animals"},
{en:"cousin",ph:"ˈkʌzən",ru:"двоюродный брат / двоюродная сестра",ex:"My cousin is visiting from abroad this summer.",lv:"A2",cat:"family"},
{en:"nephew",ph:"ˈnɛvjuː",ru:"племянник",ex:"My nephew just turned seven.",lv:"A2",cat:"family"},
{en:"niece",ph:"niːs",ru:"племянница",ex:"My niece is learning to play the piano.",lv:"A2",cat:"family"},
{en:"stepmother",ph:"ˈstɛpmʌðə",ru:"мачеха",ex:"His stepmother is a very kind woman.",lv:"A2",cat:"family"},
{en:"stepfather",ph:"ˈstɛpfɑːðə",ru:"отчим",ex:"Her stepfather taught her how to cook.",lv:"A2",cat:"family"},
{en:"partner",ph:"ˈpɑːtnə",ru:"партнёр",ex:"She introduced her partner at the party.",lv:"A2",cat:"family"},
{en:"divorce",ph:"dɪˈvɔːs",ru:"развод",ex:"They went through a difficult divorce.",lv:"A2",cat:"family"},
{en:"wedding",ph:"ˈwɛdɪŋ",ru:"свадьба",ex:"The wedding was held in a small church.",lv:"A2",cat:"family"},
{en:"pregnant",ph:"ˈprɛɡnənt",ru:"беременная",ex:"She is six months pregnant.",lv:"A2",cat:"family"},
{en:"twin",ph:"twɪn",ru:"близнец",ex:"She has twin sisters who look identical.",lv:"A2",cat:"family"},
{en:"laptop",ph:"ˈlæptɒp",ru:"ноутбук",ex:"I left my laptop at the office.",lv:"A2",cat:"technology"},
{en:"tablet",ph:"ˈtæblɪt",ru:"планшет",ex:"She reads books on her tablet.",lv:"A2",cat:"technology"},
{en:"screen",ph:"skriːn",ru:"экран",ex:"The screen is cracked and needs replacing.",lv:"A2",cat:"technology"},
{en:"password",ph:"ˈpɑːswɜːd",ru:"пароль",ex:"Please choose a strong password.",lv:"A2",cat:"technology"},
{en:"app",ph:"æp",ru:"приложение",ex:"I downloaded a new fitness app.",lv:"A2",cat:"technology"},
{en:"charger",ph:"ˈtʃɑːdʒə",ru:"зарядное устройство",ex:"I forgot my phone charger at home.",lv:"A2",cat:"technology"},
{en:"website",ph:"ˈwɛbsaɪt",ru:"сайт / веб-сайт",ex:"Check our website for more information.",lv:"A2",cat:"technology"},
{en:"message",ph:"ˈmɛsɪdʒ",ru:"сообщение",ex:"I sent him a message but he hasn't replied.",lv:"A2",cat:"technology"},
{en:"download",ph:"ˈdaʊnləʊd",ru:"скачать / загрузить",ex:"Download the update and restart your device.",lv:"A2",cat:"technology"},
{en:"printer",ph:"ˈprɪntə",ru:"принтер",ex:"The printer is out of paper.",lv:"A2",cat:"technology"},
{en:"keyboard",ph:"ˈkiːbɔːd",ru:"клавиатура",ex:"I spilled water on the keyboard.",lv:"A2",cat:"technology"},
{en:"mouse",ph:"maʊs",ru:"мышь (компьютерная)",ex:"The computer mouse is on the left side.",lv:"A2",cat:"technology"},
{en:"cable",ph:"ˈkeɪbəl",ru:"кабель / провод",ex:"We need a longer cable to reach the socket.",lv:"A2",cat:"technology"},
{en:"battery",ph:"ˈbætəri",ru:"батарея / аккумулятор",ex:"The battery runs out too quickly.",lv:"A2",cat:"technology"},
{en:"signal",ph:"ˈsɪɡnəl",ru:"сигнал",ex:"I can't make a call, there is no signal here.",lv:"A2",cat:"technology"},
{en:"concert",ph:"ˈkɒnsət",ru:"концерт",ex:"We went to a jazz concert last weekend.",lv:"A2",cat:"entertainment"},
{en:"theatre",ph:"ˈθɪətə",ru:"театр",ex:"She goes to the theatre once a month.",lv:"A2",cat:"entertainment"},
{en:"cinema",ph:"ˈsɪnɪmə",ru:"кинотеатр",ex:"The new cinema has twelve screens.",lv:"A2",cat:"entertainment"},
{en:"museum",ph:"mjuːˈzɪəm",ru:"музей",ex:"We visited the history museum on Saturday.",lv:"A2",cat:"entertainment"},
{en:"gallery",ph:"ˈɡæləri",ru:"галерея",ex:"The art gallery opens at ten.",lv:"A2",cat:"entertainment"},
{en:"festival",ph:"ˈfɛstɪvəl",ru:"фестиваль",ex:"The music festival takes place every July.",lv:"A2",cat:"entertainment"},
{en:"hobby",ph:"ˈhɒbi",ru:"хобби / увлечение",ex:"My hobby is painting.",lv:"A2",cat:"entertainment"},
{en:"dance",ph:"dɑːns",ru:"танец / танцевать",ex:"She loves to dance at parties.",lv:"A2",cat:"entertainment"},
{en:"photograph",ph:"ˈfəʊtəɡrɑːf",ru:"фотография",ex:"He took a beautiful photograph of the sunset.",lv:"A2",cat:"entertainment"},
{en:"novel",ph:"ˈnɒvəl",ru:"роман (книга)",ex:"I am reading a historical novel.",lv:"A2",cat:"entertainment"},
{en:"magazine",ph:"ˌmæɡəˈziːn",ru:"журнал",ex:"She reads a fashion magazine every week.",lv:"A2",cat:"entertainment"},
{en:"channel",ph:"ˈtʃænəl",ru:"канал",ex:"What channel is the match on?",lv:"A2",cat:"entertainment"},
{en:"programme",ph:"ˈprəʊɡræm",ru:"программа / передача",ex:"My favourite programme starts at eight.",lv:"A2",cat:"entertainment"},
{en:"exercise",ph:"ˈɛksəsaɪz",ru:"упражнение / тренировка",ex:"She does exercise every morning.",lv:"A2",cat:"entertainment"},
{en:"swimming",ph:"ˈswɪmɪŋ",ru:"плавание",ex:"I go swimming twice a week.",lv:"A2",cat:"entertainment"},
{en:"contract",ph:"ˈkɒntrækt",ru:"контракт",ex:"Read the contract carefully before signing.",lv:"A2",cat:"legal"},
{en:"law",ph:"lɔː",ru:"закон / право",ex:"Everyone must obey the law.",lv:"A2",cat:"legal"},
{en:"rights",ph:"raɪts",ru:"права",ex:"You have the right to remain silent.",lv:"A2",cat:"legal"},
{en:"document",ph:"ˈdɒkjʊmənt",ru:"документ",ex:"Do not forget to bring your identity document.",lv:"A2",cat:"legal"},
{en:"passport",ph:"ˈpɑːspɔːt",ru:"паспорт",ex:"I lost my passport at the airport.",lv:"A2",cat:"legal"},
{en:"signature",ph:"ˈsɪɡnɪtʃə",ru:"подпись",ex:"Please put your signature on the dotted line.",lv:"A2",cat:"legal"},
{en:"police",ph:"pəˈliːs",ru:"полиция",ex:"The police arrived five minutes after the call.",lv:"A2",cat:"legal"},
{en:"court",ph:"kɔːt",ru:"суд",ex:"The case will be heard in court next month.",lv:"A2",cat:"legal"},
{en:"fine",ph:"faɪn",ru:"штраф",ex:"He got a fine for parking in the wrong place.",lv:"A2",cat:"legal"},
{en:"identity",ph:"aɪˈdɛntɪti",ru:"личность / удостоверение",ex:"You need to prove your identity to enter.",lv:"A2",cat:"legal"},
{en:"permit",ph:"ˈpɜːmɪt",ru:"разрешение / пропуск",ex:"You need a permit to park here.",lv:"A2",cat:"legal"},
{en:"purple",ph:"ˈpɜːpəl",ru:"фиолетовый / пурпурный",ex:"She painted her nails purple.",lv:"A2",cat:"colors"},
{en:"silver",ph:"ˈsɪlvə",ru:"серебристый / серебряный",ex:"She wore silver earrings.",lv:"A2",cat:"colors"},
{en:"gold",ph:"ɡəʊld",ru:"золотой / золото",ex:"The frame is painted gold.",lv:"A2",cat:"colors"},
{en:"navy",ph:"ˈneɪvi",ru:"тёмно-синий",ex:"He wore a navy jacket to the meeting.",lv:"A2",cat:"colors"},
{en:"beige",ph:"beɪʒ",ru:"бежевый",ex:"The walls are painted a light beige.",lv:"A2",cat:"colors"},
{en:"turquoise",ph:"ˈtɜːkwɔɪz",ru:"бирюзовый",ex:"She wore a turquoise scarf.",lv:"A2",cat:"colors"},
{en:"cream",ph:"kriːm",ru:"кремовый",ex:"The sofa is cream with gold cushions.",lv:"A2",cat:"colors"},
{en:"dark",ph:"dɑːk",ru:"тёмный",ex:"I prefer dark colours in winter.",lv:"A2",cat:"colors"},
{en:"light",ph:"laɪt",ru:"светлый / свет",ex:"Light blue is her favourite colour.",lv:"A2",cat:"colors"},
{en:"pale",ph:"peɪl",ru:"бледный / светлый",ex:"She looks pale, are you feeling alright?",lv:"A2",cat:"colors"},
{en:"million",ph:"ˈmɪljən",ru:"миллион",ex:"The city has over a million inhabitants.",lv:"A2",cat:"numbers"},
{en:"thousand",ph:"ˈθaʊzənd",ru:"тысяча",ex:"There were thousands of people at the stadium.",lv:"A2",cat:"numbers"},
{en:"half",ph:"hɑːf",ru:"половина",ex:"She ate half of the pizza.",lv:"A2",cat:"numbers"},
{en:"quarter",ph:"ˈkwɔːtə",ru:"четверть",ex:"It is a quarter past three.",lv:"A2",cat:"numbers"},
{en:"double",ph:"ˈdʌbəl",ru:"двойной / удвоить",ex:"He earns double the average salary.",lv:"A2",cat:"numbers"},
{en:"third",ph:"θɜːd",ru:"третий",ex:"She lives on the third floor.",lv:"A2",cat:"numbers"},
{en:"dozen",ph:"ˈdʌzən",ru:"дюжина",ex:"I bought a dozen eggs at the shop.",lv:"A2",cat:"numbers"},
{en:"couple",ph:"ˈkʌpəl",ru:"пара / несколько",ex:"I'll be ready in a couple of minutes.",lv:"A2",cat:"numbers"},
{en:"average",ph:"ˈævərɪdʒ",ru:"средний / в среднем",ex:"The average temperature in July is thirty degrees.",lv:"A2",cat:"numbers"},
{en:"total",ph:"ˈtəʊtəl",ru:"итог / итоговый / всего",ex:"The total cost comes to eighty euros.",lv:"A2",cat:"numbers"},
{en:"shoulder",ph:"ˈʃəʊldə",ru:"плечо",ex:"She tapped him on the shoulder.",lv:"A2",cat:"body"},
{en:"knee",ph:"niː",ru:"колено",ex:"He hurt his knee during the match.",lv:"A2",cat:"body"},
{en:"chin",ph:"tʃɪn",ru:"подбородок",ex:"He rested his chin on his hand.",lv:"A2",cat:"body"},
{en:"cheek",ph:"tʃiːk",ru:"щека",ex:"The baby has chubby cheeks.",lv:"A2",cat:"body"},
{en:"forehead",ph:"ˈfɒrɪd",ru:"лоб",ex:"She felt his forehead to check for fever.",lv:"A2",cat:"body"},
{en:"chest",ph:"tʃɛst",ru:"грудь",ex:"He felt a pain in his chest.",lv:"A2",cat:"body"},
{en:"wrist",ph:"rɪst",ru:"запястье",ex:"She wears a gold bracelet on her wrist.",lv:"A2",cat:"body"},
{en:"elbow",ph:"ˈɛlbəʊ",ru:"локоть",ex:"He bumped his elbow on the table.",lv:"A2",cat:"body"},
{en:"ankle",ph:"ˈæŋkəl",ru:"лодыжка",ex:"She twisted her ankle on the steps.",lv:"A2",cat:"body"},
{en:"thumb",ph:"θʌm",ru:"большой палец",ex:"He hurt his thumb while cooking.",lv:"A2",cat:"body"},
{en:"nail",ph:"neɪl",ru:"ноготь / гвоздь",ex:"She painted her nails red.",lv:"A2",cat:"body"},
{en:"skin",ph:"skɪn",ru:"кожа",ex:"Use sunscreen to protect your skin.",lv:"A2",cat:"body"},
{en:"bone",ph:"bəʊn",ru:"кость",ex:"He broke a bone in his hand.",lv:"A2",cat:"body"},
{en:"muscle",ph:"ˈmʌsəl",ru:"мышца",ex:"Regular exercise builds strong muscles.",lv:"A2",cat:"body"},
{en:"throat",ph:"θrəʊt",ru:"горло",ex:"My throat is sore and it hurts to swallow.",lv:"A2",cat:"body"},
{en:"neighbour",ph:"ˈneɪbə",ru:"сосед",ex:"I borrowed some sugar from my neighbour.",lv:"A2",cat:"daily"},
{en:"environment",ph:"ɪnˈvaɪərənmənt",ru:"окружающая среда / обстановка",ex:"We must protect our environment.",lv:"A2",cat:"daily"},
{en:"problem",ph:"ˈprɒbləm",ru:"проблема",ex:"We need to solve this problem quickly.",lv:"A2",cat:"daily"},
{en:"answer",ph:"ˈɑːnsə",ru:"ответ / отвечать",ex:"I don't know the answer to your question.",lv:"A2",cat:"daily"},
{en:"reason",ph:"ˈriːzən",ru:"причина",ex:"What is the reason for the delay?",lv:"A2",cat:"daily"},
{en:"idea",ph:"aɪˈdɪə",ru:"идея",ex:"That is a great idea!",lv:"A2",cat:"daily"},
{en:"plan",ph:"plæn",ru:"план",ex:"Do you have any plans for the weekend?",lv:"A2",cat:"daily"},
{en:"information",ph:"ˌɪnfəˈmeɪʃən",ru:"информация",ex:"Where can I get more information?",lv:"A2",cat:"daily"},
{en:"news",ph:"njuːz",ru:"новости",ex:"Have you heard the latest news?",lv:"A2",cat:"daily"},
{en:"language",ph:"ˈlæŋɡwɪdʒ",ru:"язык",ex:"She is learning a new language.",lv:"A2",cat:"daily"},
{en:"culture",ph:"ˈkʌltʃə",ru:"культура",ex:"Learning about local culture is important.",lv:"A2",cat:"daily"},
{en:"travel",ph:"ˈtrævəl",ru:"путешествие / путешествовать",ex:"She loves to travel to new countries.",lv:"A2",cat:"daily"},
{en:"holiday",ph:"ˈhɒlɪdeɪ",ru:"каникулы / отпуск / праздник",ex:"We spent our holiday in Italy.",lv:"A2",cat:"daily"},
{en:"hotel",ph:"həʊˈtɛl",ru:"гостиница / отель",ex:"We stayed at a five-star hotel.",lv:"A2",cat:"daily"},
{en:"restaurant",ph:"ˈrɛstərɒnt",ru:"ресторан",ex:"Let's try that new Italian restaurant.",lv:"A2",cat:"daily"},
{en:"waiter",ph:"ˈweɪtə",ru:"официант",ex:"The waiter brought the menu immediately.",lv:"A2",cat:"work"},
{en:"chef",ph:"ʃɛf",ru:"шеф-повар",ex:"The chef prepared a special dish for us.",lv:"A2",cat:"work"},
{en:"teacher",ph:"ˈtiːtʃə",ru:"учитель",ex:"My teacher explains grammar very clearly.",lv:"A2",cat:"work"},
{en:"engineer",ph:"ˌɛndʒɪˈnɪə",ru:"инженер",ex:"He works as a software engineer.",lv:"A2",cat:"work"},
{en:"lawyer",ph:"ˈlɔːjə",ru:"юрист / адвокат",ex:"She called her lawyer for advice.",lv:"A2",cat:"work"},
{en:"accountant",ph:"əˈkaʊntənt",ru:"бухгалтер",ex:"The company hired a new accountant.",lv:"A2",cat:"work"},
{en:"architect",ph:"ˈɑːkɪtɛkt",ru:"архитектор",ex:"The architect designed a beautiful building.",lv:"A2",cat:"work"},
{en:"journalist",ph:"ˈdʒɜːnəlɪst",ru:"журналист",ex:"The journalist asked difficult questions.",lv:"A2",cat:"work"},
{en:"pharmacist",ph:"ˈfɑːməsɪst",ru:"фармацевт",ex:"The pharmacist explained how to take the tablets.",lv:"A2",cat:"work"},
{en:"scientist",ph:"ˈsaɪəntɪst",ru:"учёный",ex:"The scientists made an important discovery.",lv:"A2",cat:"work"},
{en:"flight",ph:"flaɪt",ru:"рейс / полёт",ex:"Our flight was delayed by two hours.",lv:"A2",cat:"transport"},
{en:"platform",ph:"ˈplætfɔːm",ru:"платформа / перрон",ex:"The train departs from platform three.",lv:"A2",cat:"transport"},
{en:"helicopter",ph:"ˈhɛlɪkɒptə",ru:"вертолёт",ex:"A helicopter landed in the field.",lv:"A2",cat:"transport"},
{en:"sailboat",ph:"ˈseɪlbəʊt",ru:"парусная лодка",ex:"He rents a sailboat in summer.",lv:"A2",cat:"transport"},
{en:"bicycle lane",ph:"ˈbaɪsɪkəl leɪn",ru:"велосипедная дорожка",ex:"Use the bicycle lane on the right.",lv:"A2",cat:"transport"},
{en:"roundabout",ph:"ˈraʊndəbaʊt",ru:"круговое движение",ex:"Turn left at the roundabout.",lv:"A2",cat:"transport"},
{en:"crossroads",ph:"ˈkrɒsrəʊdz",ru:"перекрёсток",ex:"Turn right at the crossroads.",lv:"A2",cat:"transport"},
{en:"reverse",ph:"rɪˈvɜːs",ru:"задний ход / разворот",ex:"She reversed the car into the parking space.",lv:"A2",cat:"transport"},
{en:"accelerate",ph:"əkˈsɛləreɪt",ru:"ускоряться",ex:"Do not accelerate near a school.",lv:"A2",cat:"transport"},
{en:"brake",ph:"breɪk",ru:"тормоз / тормозить",ex:"He pressed the brake too late.",lv:"A2",cat:"transport"},
{en:"insurance",ph:"ɪnˈʃʊərəns",ru:"страховка / страхование",ex:"You must have car insurance to drive legally.",lv:"A2",cat:"legal"},
{en:"witness",ph:"ˈwɪtnɪs",ru:"свидетель",ex:"The witness described what he saw.",lv:"A2",cat:"legal"},
{en:"complaint",ph:"kəmˈpleɪnt",ru:"жалоба",ex:"She filed a complaint with the manager.",lv:"A2",cat:"legal"},
{en:"evidence",ph:"ˈɛvɪdəns",ru:"доказательство / улика",ex:"The evidence was presented in court.",lv:"A2",cat:"legal"},
{en:"victim",ph:"ˈvɪktɪm",ru:"жертва",ex:"The victim was taken to hospital.",lv:"A2",cat:"legal"},
{en:"arrest",ph:"əˈrɛst",ru:"арест / арестовать",ex:"The police made an arrest last night.",lv:"A2",cat:"legal"},
{en:"lawyer",ph:"ˈlɔːjə",ru:"адвокат",ex:"Everyone has the right to a lawyer.",lv:"A2",cat:"legal"},
{en:"judge",ph:"dʒʌdʒ",ru:"судья",ex:"The judge read out the verdict.",lv:"A2",cat:"legal"},
{en:"regulation",ph:"ˌrɛɡjʊˈleɪʃən",ru:"правило / регламент",ex:"All companies must follow safety regulations.",lv:"A2",cat:"legal"},
{en:"agreement",ph:"əˈɡriːmənt",ru:"соглашение / договор",ex:"Both sides signed the agreement.",lv:"A2",cat:"legal"},
{en:"vitamin",ph:"ˈvɪtəmɪn",ru:"витамин",ex:"Take your vitamins every morning.",lv:"A2",cat:"medical"},
{en:"bandage",ph:"ˈbændɪdʒ",ru:"бинт / повязка",ex:"The nurse wrapped a bandage around his wrist.",lv:"A2",cat:"medical"},
{en:"cough",ph:"kɒf",ru:"кашель / кашлять",ex:"She has a bad cough this week.",lv:"A2",cat:"medical"},
{en:"sneeze",ph:"sniːz",ru:"чихание / чихать",ex:"He sneezed several times in the morning.",lv:"A2",cat:"medical"},
{en:"dizzy",ph:"ˈdɪzi",ru:"головокружение / кружится голова",ex:"I felt dizzy after standing up too fast.",lv:"A2",cat:"medical"},
{en:"swollen",ph:"ˈswəʊlən",ru:"опухший / воспалённый",ex:"Her ankle is swollen after the fall.",lv:"A2",cat:"medical"},
{en:"tablet",ph:"ˈtæblɪt",ru:"таблетка",ex:"Take one tablet three times a day.",lv:"A2",cat:"medical"},
{en:"diet",ph:"ˈdaɪət",ru:"диета",ex:"She is on a strict diet this month.",lv:"A2",cat:"medical"},
{en:"health",ph:"hɛlθ",ru:"здоровье",ex:"Good food and sleep are important for health.",lv:"A2",cat:"medical"},
{en:"weight",ph:"weɪt",ru:"вес",ex:"He lost five kilograms of weight.",lv:"A2",cat:"medical"},
{en:"electric",ph:"ɪˈlɛktrɪk",ru:"электрический",ex:"They drive an electric car.",lv:"A2",cat:"technology"},
{en:"solar",ph:"ˈsəʊlə",ru:"солнечный (энергия)",ex:"They installed solar panels on the roof.",lv:"A2",cat:"technology"},
{en:"remote control",ph:"rɪˈməʊt kənˈtrəʊl",ru:"пульт дистанционного управления",ex:"Where is the remote control for the TV?",lv:"A2",cat:"technology"},
{en:"microwave",ph:"ˈmaɪkrəweɪv",ru:"микроволновка",ex:"Heat the soup in the microwave for two minutes.",lv:"A2",cat:"technology"},
{en:"headphones",ph:"ˈhɛdfəʊnz",ru:"наушники",ex:"She put on her headphones and listened to music.",lv:"A2",cat:"technology"},
{en:"speaker",ph:"ˈspiːkə",ru:"динамик / колонка",ex:"The speaker in my phone is broken.",lv:"A2",cat:"technology"},
{en:"connection",ph:"kəˈnɛkʃən",ru:"соединение / подключение",ex:"The wifi connection is very fast here.",lv:"A2",cat:"technology"},
{en:"update",ph:"ˈʌpdeɪt",ru:"обновление / обновить",ex:"Please install the latest software update.",lv:"A2",cat:"technology"},
{en:"virus",ph:"ˈvaɪərəs",ru:"вирус",ex:"My computer has a virus.",lv:"A2",cat:"technology"},
{en:"cloud storage",ph:"klaʊd ˈstɔːrɪdʒ",ru:"облачное хранилище",ex:"I back up my photos to cloud storage.",lv:"A2",cat:"technology"},
{en:"choir",ph:"ˈkwaɪə",ru:"хор",ex:"She sings in the school choir.",lv:"A2",cat:"entertainment"},
{en:"comedy",ph:"ˈkɒmɪdi",ru:"комедия",ex:"We watched a comedy film last night.",lv:"A2",cat:"entertainment"},
{en:"drama",ph:"ˈdrɑːmə",ru:"драма",ex:"The drama club meets every Thursday.",lv:"A2",cat:"entertainment"},
{en:"sculpture",ph:"ˈskʌlptʃə",ru:"скульптура",ex:"She admired the sculpture in the park.",lv:"A2",cat:"entertainment"},
{en:"exhibition",ph:"ˌɛksɪˈbɪʃən",ru:"выставка",ex:"I visited the photography exhibition downtown.",lv:"A2",cat:"entertainment"},
{en:"applaud",ph:"əˈplɔːd",ru:"аплодировать",ex:"The audience applauded at the end of the show.",lv:"A2",cat:"entertainment"},
{en:"rehearsal",ph:"rɪˈhɜːsəl",ru:"репетиция",ex:"The band has a rehearsal tomorrow night.",lv:"A2",cat:"entertainment"},
{en:"audience",ph:"ˈɔːdiəns",ru:"зрители / аудитория",ex:"The audience cheered loudly.",lv:"A2",cat:"entertainment"},
{en:"cartoon",ph:"kɑːˈtuːn",ru:"мультфильм",ex:"My son watches cartoons every morning.",lv:"A2",cat:"entertainment"},
{en:"adventure",ph:"ədˈvɛntʃə",ru:"приключение",ex:"The book is about a boy's adventure at sea.",lv:"A2",cat:"entertainment"},
{en:"camping",ph:"ˈkæmpɪŋ",ru:"кемпинг / поход",ex:"We went camping in the mountains last summer.",lv:"A2",cat:"entertainment"},
{en:"stadium",ph:"ˈsteɪdiəm",ru:"стадион",ex:"The stadium holds fifty thousand fans.",lv:"A2",cat:"entertainment"},
{en:"chess",ph:"tʃɛs",ru:"шахматы",ex:"He plays chess with his father on weekends.",lv:"A2",cat:"entertainment"},
{en:"puzzle",ph:"ˈpʌzəl",ru:"головоломка / пазл",ex:"She enjoys doing jigsaw puzzles.",lv:"A2",cat:"entertainment"},
{en:"exhibition",ph:"ˌɛksɪˈbɪʃən",ru:"выставка",ex:"The art exhibition opened last Friday.",lv:"A2",cat:"entertainment"},
{en:"rent",ph:"rɛnt",ru:"аренда / снимать жильё",ex:"How much is the monthly rent?",lv:"A2",cat:"bank"},
{en:"budget",ph:"ˈbʌdʒɪt",ru:"бюджет",ex:"We need to stick to our budget this month.",lv:"A2",cat:"bank"},
{en:"savings",ph:"ˈseɪvɪŋz",ru:"сбережения",ex:"She puts some money into savings each month.",lv:"A2",cat:"bank"},
{en:"tax",ph:"tæks",ru:"налог",ex:"The price includes all taxes.",lv:"A2",cat:"bank"},
{en:"fee",ph:"fiː",ru:"комиссия / сбор / плата",ex:"There is a monthly fee for the service.",lv:"A2",cat:"bank"},
{en:"exchange rate",ph:"ɪksˈtʃeɪndʒ reɪt",ru:"обменный курс",ex:"Check the exchange rate before converting money.",lv:"A2",cat:"bank"},
{en:"cheque",ph:"tʃɛk",ru:"чек (банковский)",ex:"He paid by cheque.",lv:"A2",cat:"bank"},
{en:"charity",ph:"ˈtʃærɪti",ru:"благотворительность",ex:"They donate to a local charity every year.",lv:"A2",cat:"bank"},
{en:"profit",ph:"ˈprɒfɪt",ru:"прибыль",ex:"The company made a large profit this year.",lv:"A2",cat:"bank"},
{en:"debt",ph:"dɛt",ru:"долг",ex:"She is trying to pay off her credit card debt.",lv:"A2",cat:"bank"},
{en:"nationality",ph:"ˌnæʃəˈnælɪti",ru:"национальность / гражданство",ex:"What nationality is she?",lv:"A2",cat:"daily"},
{en:"border control",ph:"ˈbɔːdə kənˈtrəʊl",ru:"пограничный контроль",ex:"We waited an hour at border control.",lv:"A2",cat:"legal"},
{en:"residence",ph:"ˈrɛzɪdəns",ru:"место жительства / резиденция",ex:"Please state your country of residence.",lv:"A2",cat:"legal"},
{en:"visa",ph:"ˈviːzə",ru:"виза",ex:"She applied for a tourist visa.",lv:"A2",cat:"legal"},
{en:"embassy",ph:"ˈɛmbəsi",ru:"посольство",ex:"I need to visit the embassy to renew my passport.",lv:"A2",cat:"legal"},
{en:"citizenship",ph:"ˈsɪtɪzənʃɪp",ru:"гражданство",ex:"He applied for citizenship last year.",lv:"A2",cat:"legal"},
{en:"permission",ph:"pəˈmɪʃən",ru:"разрешение",ex:"You need permission to enter this area.",lv:"A2",cat:"legal"},
{en:"rent agreement",ph:"rɛnt əˈɡriːmənt",ru:"договор аренды",ex:"Sign the rent agreement before moving in.",lv:"A2",cat:"legal"},
{en:"humid",ph:"ˈhjuːmɪd",ru:"влажный",ex:"The weather is very humid in August.",lv:"A2",cat:"weather"},
{en:"breeze",ph:"briːz",ru:"бриз / лёгкий ветер",ex:"A cool breeze came from the sea.",lv:"A2",cat:"weather"},
{en:"frost",ph:"frɒst",ru:"мороз / иней",ex:"There was a heavy frost last night.",lv:"A2",cat:"weather"},
{en:"slippery",ph:"ˈslɪpəri",ru:"скользкий",ex:"The roads are slippery after the ice storm.",lv:"A2",cat:"weather"},
{en:"snowfall",ph:"ˈsnəʊfɔːl",ru:"снегопад",ex:"Heavy snowfall is expected tonight.",lv:"A2",cat:"weather"},
{en:"sunshine",ph:"ˈsʌnʃaɪn",ru:"солнечный свет / солнышко",ex:"We enjoyed the sunshine on the beach.",lv:"A2",cat:"weather"},
{en:"degree",ph:"dɪˈɡriː",ru:"градус",ex:"It is minus ten degrees outside.",lv:"A2",cat:"weather"},
{en:"pressure",ph:"ˈprɛʃə",ru:"давление",ex:"High pressure brings clear skies.",lv:"A2",cat:"weather"},
{en:"avalanche",ph:"ˈævəlɑːnʃ",ru:"лавина",ex:"An avalanche blocked the mountain road.",lv:"A2",cat:"weather"},
{en:"drought",ph:"draʊt",ru:"засуха",ex:"The region suffered a drought for three months.",lv:"A2",cat:"weather"},
{en:"lion",ph:"ˈlaɪən",ru:"лев",ex:"The lion roared loudly in the savanna.",lv:"A2",cat:"animals"},
{en:"tiger",ph:"ˈtaɪɡə",ru:"тигр",ex:"Tigers are endangered animals.",lv:"A2",cat:"animals"},
{en:"elephant",ph:"ˈɛlɪfənt",ru:"слон",ex:"The elephant used its trunk to drink water.",lv:"A2",cat:"animals"},
{en:"giraffe",ph:"dʒɪˈrɑːf",ru:"жираф",ex:"The giraffe ate leaves from the tall tree.",lv:"A2",cat:"animals"},
{en:"crocodile",ph:"ˈkrɒkədaɪl",ru:"крокодил",ex:"The crocodile lay still near the river.",lv:"A2",cat:"animals"},
{en:"dolphin",ph:"ˈdɒlfɪn",ru:"дельфин",ex:"Dolphins are very intelligent animals.",lv:"A2",cat:"animals"},
{en:"whale",ph:"weɪl",ru:"кит",ex:"We saw a whale on the boat trip.",lv:"A2",cat:"animals"},
{en:"penguin",ph:"ˈpɛŋɡwɪn",ru:"пингвин",ex:"Penguins live in Antarctica.",lv:"A2",cat:"animals"},
{en:"monkey",ph:"ˈmʌŋki",ru:"обезьяна",ex:"The monkey swung from branch to branch.",lv:"A2",cat:"animals"},
{en:"camel",ph:"ˈkæməl",ru:"верблюд",ex:"Camels can survive for days without water.",lv:"A2",cat:"animals"},
{en:"mosquito",ph:"məˈskiːtəʊ",ru:"комар",ex:"A mosquito bit me on the neck.",lv:"A2",cat:"animals"},
{en:"squirrel",ph:"ˈskwɪrəl",ru:"белка",ex:"A squirrel collected nuts in the park.",lv:"A2",cat:"animals"},
{en:"pigeon",ph:"ˈpɪdʒɪn",ru:"голубь",ex:"Pigeons gather near the fountain every day.",lv:"A2",cat:"animals"},
{en:"tortoise",ph:"ˈtɔːtəs",ru:"черепаха",ex:"The tortoise moved slowly across the garden.",lv:"A2",cat:"animals"},
{en:"hamster",ph:"ˈhæmstə",ru:"хомяк",ex:"My daughter has a hamster in a cage.",lv:"A2",cat:"animals"},
{en:"achievement",ph:"əˈtʃiːvmənt",ru:"достижение",ex:"Graduating was a great achievement for her.",lv:"A2",cat:"daily"},
{en:"relationship",ph:"rɪˈleɪʃənʃɪp",ru:"отношения / связь",ex:"They have a very close relationship.",lv:"A2",cat:"daily"},
{en:"memory",ph:"ˈmɛməri",ru:"память / воспоминание",ex:"I have many happy memories from my childhood.",lv:"A2",cat:"daily"},
{en:"opinion",ph:"əˈpɪnjən",ru:"мнение",ex:"In my opinion, we should leave earlier.",lv:"A2",cat:"daily"},
{en:"decision",ph:"dɪˈsɪʒən",ru:"решение",ex:"Making good decisions takes time.",lv:"A2",cat:"daily"},
{en:"experience",ph:"ɪkˈspɪəriəns",ru:"опыт",ex:"Travelling gives you new experiences.",lv:"A2",cat:"daily"},
{en:"difference",ph:"ˈdɪfərəns",ru:"разница / различие",ex:"There is a big difference between the two.",lv:"A2",cat:"daily"},
{en:"opportunity",ph:"ˌɒpəˈtjuːnɪti",ru:"возможность / шанс",ex:"This is a great opportunity to learn.",lv:"A2",cat:"daily"},
{en:"mistake",ph:"mɪˈsteɪk",ru:"ошибка",ex:"Everyone makes mistakes sometimes.",lv:"A2",cat:"daily"},
{en:"choice",ph:"tʃɔɪs",ru:"выбор",ex:"It is your choice, I will support you.",lv:"A2",cat:"daily"},
{en:"effort",ph:"ˈɛfət",ru:"усилие / старание",ex:"She put a lot of effort into her project.",lv:"A2",cat:"daily"},
{en:"success",ph:"səkˈsɛs",ru:"успех",ex:"Hard work leads to success.",lv:"A2",cat:"daily"},
{en:"behaviour",ph:"bɪˈheɪvjə",ru:"поведение",ex:"His behaviour in class has improved.",lv:"A2",cat:"daily"},
{en:"advantage",ph:"ədˈvɑːntɪdʒ",ru:"преимущество",ex:"There are many advantages to living near work.",lv:"A2",cat:"daily"},
{en:"service",ph:"ˈsɜːvɪs",ru:"услуга / обслуживание",ex:"The service in this restaurant is excellent.",lv:"A2",cat:"daily"},
{en:"customer",ph:"ˈkʌstəmə",ru:"клиент / покупатель",ex:"The customer complained about the order.",lv:"A2",cat:"shopping"},
{en:"delivery",ph:"dɪˈlɪvəri",ru:"доставка",ex:"The delivery arrived the next day.",lv:"A2",cat:"shopping"},
{en:"order",ph:"ˈɔːdə",ru:"заказ / заказывать",ex:"I placed an order online this morning.",lv:"A2",cat:"shopping"},
{en:"stock",ph:"stɒk",ru:"запас / товарный запас",ex:"Sorry, this size is out of stock.",lv:"A2",cat:"shopping"},
{en:"guarantee",ph:"ˌɡærənˈtiː",ru:"гарантия",ex:"The product comes with a one-year guarantee.",lv:"A2",cat:"shopping"},
{en:"refund",ph:"ˈriːfʌnd",ru:"возврат денег",ex:"She got a full refund for the broken item.",lv:"A2",cat:"shopping"},
{en:"brand",ph:"brænd",ru:"бренд / марка",ex:"What brand of phone do you have?",lv:"A2",cat:"shopping"},
{en:"quality",ph:"ˈkwɒlɪti",ru:"качество",ex:"The quality of this jacket is very good.",lv:"A2",cat:"shopping"},
{en:"offer",ph:"ˈɒfə",ru:"предложение / акция",ex:"There is a special offer on shoes this week.",lv:"A2",cat:"shopping"},
{en:"bargain",ph:"ˈbɑːɡɪn",ru:"выгодная покупка / торговаться",ex:"She found a real bargain at the market.",lv:"A2",cat:"shopping"},
{en:"responsible",ph:"rɪˈspɒnsɪbəl",ru:"ответственный",ex:"She is very responsible at work.",lv:"A2",cat:"work"},
{en:"promotion",ph:"prəˈməʊʃən",ru:"повышение / акция",ex:"He got a promotion after two years.",lv:"A2",cat:"work"},
{en:"application",ph:"ˌæplɪˈkeɪʃən",ru:"заявление / приложение",ex:"She submitted her job application on time.",lv:"A2",cat:"work"},
{en:"profession",ph:"prəˈfɛʃən",ru:"профессия",ex:"What is your profession?",lv:"A2",cat:"work"},
{en:"task",ph:"tɑːsk",ru:"задача / задание",ex:"I have several tasks to complete today.",lv:"A2",cat:"work"},
{en:"achievement",ph:"əˈtʃiːvmənt",ru:"достижение",ex:"She listed her achievements in her CV.",lv:"A2",cat:"work"},
{en:"policy",ph:"ˈpɒlɪsi",ru:"политика / правила",ex:"The company has a strict privacy policy.",lv:"A2",cat:"work"},
{en:"training",ph:"ˈtreɪnɪŋ",ru:"обучение / тренинг",ex:"All new employees must complete a training course.",lv:"A2",cat:"work"},
{en:"feedback",ph:"ˈfiːdbæk",ru:"обратная связь / отзыв",ex:"Her manager gave her positive feedback.",lv:"A2",cat:"work"},
{en:"resignation",ph:"ˌrɛzɪɡˈneɪʃən",ru:"увольнение по собственному желанию",ex:"He handed in his resignation last Friday.",lv:"A2",cat:"work"},
"""
